### ISSUE TITLE
How do I use RegularExpressionTextExtraction to extract multiple sections?

### ISSUE THREAD

**Issue by burton666** [jorisschellekens/borb#100]
I can see in the examples how to extract a single part of a text using RegularExpressionTextExtraction. But how do I extract multiple parts of text in the same way ?

**Comment by jorisschellekens** [comment]
This repository has issue templates to ensure I don't have to ask the same questions every time someone asks something.

- What have you tried? Show me your code
- Show me your input document
- What would you expect the output to be?

Also, keep in mind the issues here are meant to report bugs, or request features. You are not asking for any of that. You're asking "how do I do this?".

Further actions:
- Ask on StackOverflow 
- Create an issue by following the template

I will close this issue.

Kind regards,
Joris Schellekens
