### ISSUE TITLE
Automatic Function and Class API Documentation

### ISSUE THREAD

**Issue by Rowlando13** [jorisschellekens/borb#102]
My feature request is related to using borb and trying to find the correct import statements. For example, I was looking for your PageSize enumerator but I could not see from your documentation where to import it from. 

I would like Borb to have automatically generated API docs using something like sphinx and readthedocs. To be clear I am just asking for function and class references generated from docstrings. Something like the Python [os module function definitions](https://docs.python.org/3/library/os.html#os.fsencode). This would enable nice searching and make the package structure more understandable.

The current alternative is to search within the github repo. The alternative just seems inelegant for such a well constructed and documented package. Another alternative is to carefully note the import statements in the existing documentation. The downside is that is very manual and not super searchable unless you download it all.

**Comment by jorisschellekens** [comment]
I'm bit against setting up documentation. But I do wonder why you aren't using an IDE that simply provides you with a tool tip whenever you need an import.

I use Pycharm (Community Edition). And as soon as I type something like `PDF.dumps` I am offered the option (via context menu) of adding the imports.

**Comment by Rowlando13** [comment]
I had not thought about automatic imports. Thanks for bringing them up. I always write out the import first then use the function/class/module, so it just never come up. Upon closer inspection and some research, I think you have identified a place where Pycharm is just better than VS Code (what I use). VS Code auto imports work well for the standard library and not very well for third party packages. There are some work arounds, but they time consuming to figure out.  
I think what you have identified drops the priority of this some. I am okay if you want to flag it as low priority and see if someone else asks for it.

**Comment by jorisschellekens** [comment]
As a side note, I have also made the most often used imports more easy. 

Classes like `Document`, `Page` or `PageLayout` can be imported (in the easier way) by writing `from borb.pdf import X`

I am going to close this ticket, and if more people ask I'll revisit it.

Kind regards,
Joris Schellekens
