### ISSUE TITLE
cannot get it to work - list index out of range error

### ISSUE THREAD

**Issue by remar1972** [jorisschellekens/borb#105]
I am not sure this is a bug so forgive me for being a noob and for possibly reporting something that is nog an issue but pure ignorance from my side

With your example in the simplest form I am trying to read a PDF invoice. This results in a "list index out of range error"

Here is my code:

```
import typing
from borb.pdf import Document
from borb.pdf.pdf import PDF
import os

def main():
    d: typing.Optional[Document] = None
    with open("output.pdf", "rb") as pdf_in_handle:
        d = PDF.loads(pdf_in_handle)

    assert d is not None


if __name__ == "__main__":
    main()
```

Here is the error message:

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
Input In [3], in <cell line: 1>()
----> 1 main()

Input In [2], in main()
      2 d: typing.Optional[Document] = None
      3 with open("output.pdf", "rb") as pdf_in_handle:
----> 4     d = PDF.loads(pdf_in_handle)
      6 assert d is not None

File c:\users\python\sites\pdf\venv\lib\site-packages\borb-2.0.26-py3.9.egg\borb\pdf\pdf.py:54, in PDF.loads(file, event_listeners, password)
     44 @staticmethod
     45 def loads(
     46     file: Union[io.BufferedIOBase, io.RawIOBase],
     47     event_listeners: List[EventListener] = [],
     48     password: typing.Optional[str] = None,
     49 ) -> Document:
     50     """
     51     This function reads a byte-stream input (which may be presented as an io.BufferedIOBase o io.RawIOBase)
     52     and returns a Document.
     53     """
---> 54     return ReadAnyObjectTransformer().transform(
     55         file,
     56         parent_object=None,
     57         context=ReadTransformerState(password=password),
     58         event_listeners=event_listeners,
     59     )

File c:\users\python\sites\pdf\venv\lib\site-packages\borb-2.0.26-py3.9.egg\borb\io\read\any_object_transformer.py:100, in AnyObjectTransformer.transform(self, object_to_transform, parent_object, context, event_listeners)
     93     return super().transform(
     94         object_to_transform,
     95         parent_object,
     96         ReadTransformerState(),
     97         event_listeners,
     98     )
     99 else:
--> 100     return super().transform(
    101         object_to_transform, parent_object, context, event_listeners
    102     )

File c:\users\python\sites\pdf\venv\lib\site-packages\borb-2.0.26-py3.9.egg\borb\io\read\transformer.py:123, in Transformer.transform(self, object_to_transform, parent_object, context, event_listeners)
    121 self._level += 1
    122 self._invocation_count += 1
--> 123 out = h.transform(
    124     object_to_transform,
    125     parent_object=parent_object,
    126     context=context,
    127     event_listeners=event_listeners,
    128 )
    129 self._level -= 1
    130 # print("%s</%s>" % ("   " * self.level, h.__class__.__name__))

File c:\users\python\sites\pdf\venv\lib\site-packages\borb-2.0.26-py3.9.egg\borb\io\read\reference\xref_transformer.py:140, in XREFTransformer.transform(self, object_to_transform, parent_object, context, event_listeners)
    135     raise NotImplementedError(
    136         "password-protected PDFs are currently not supported"
    137     )
    139 # transform /Trailer
--> 140 trailer = self.get_root_transformer().transform(
    141     context.root_object["XRef"]["Trailer"],
    142     context.root_object,
    143     context,
    144     event_listeners,
    145 )
    147 assert trailer is not None
    148 assert isinstance(trailer, Dictionary)

File c:\users\python\sites\pdf\venv\lib\site-packages\borb-2.0.26-py3.9.egg\borb\io\read\any_object_transformer.py:100, in AnyObjectTransformer.transform(self, object_to_transform, parent_object, context, event_listeners)
     93     return super().transform(
     94         object_to_transform,
     95         parent_object,
     96         ReadTransformerState(),
     97         event_listeners,
     98     )
     99 else:
--> 100     return super().transform(
    101         object_to_transform, parent_object, context, event_listeners
    102     )

File c:\users\python\sites\pdf\venv\lib\site-packages\borb-2.0.26-py3.9.egg\borb\io\read\transformer.py:123, in Transformer.transform(self, object_to_transform, parent_object, context, event_listeners)
    121 self._level += 1
    122 self._invocation_count += 1
--> 123 out = h.transform(
    124     object_to_transform,
    125     parent_object=parent_object,
    126     context=context,
    127     event_listeners=event_listeners,
    128 )
    129 self._level -= 1
    130 # print("%s</%s>" % ("   " * self.level, h.__class__.__name__))

File c:\users\python\sites\pdf\venv\lib\site-packages\borb-2.0.26-py3.9.egg\borb\io\read\object\dictionary_transformer.py:48, in DictionaryTransformer.transform(self, object_to_transform, parent_object, context, event_listeners)
     46 # transform key/value pair(s)
     47 for k, v in object_to_transform.items():
---> 48     v = self.get_root_transformer().transform(
     49         v, object_to_transform, context, event_listeners
     50     )
     51     if v is not None:
     52         object_to_transform[k] = v

File c:\users\python\sites\pdf\venv\lib\site-packages\borb-2.0.26-py3.9.egg\borb\io\read\any_object_transformer.py:100, in AnyObjectTransformer.transform(self, object_to_transform, parent_object, context, event_listeners)
     93     return super().transform(
     94         object_to_transform,
     95         parent_object,
     96         ReadTransformerState(),
     97         event_listeners,
     98     )
     99 else:
--> 100     return super().transform(
    101         object_to_transform, parent_object, context, event_listeners
    102     )

File c:\users\python\sites\pdf\venv\lib\site-packages\borb-2.0.26-py3.9.egg\borb\io\read\transformer.py:123, in Transformer.transform(self, object_to_transform, parent_object, context, event_listeners)
    121 self._level += 1
    122 self._invocation_count += 1
--> 123 out = h.transform(
    124     object_to_transform,
    125     parent_object=parent_object,
    126     context=context,
    127     event_listeners=event_listeners,
    128 )
    129 self._level -= 1
    130 # print("%s</%s>" % ("   " * self.level, h.__class__.__name__))

File c:\users\python\sites\pdf\venv\lib\site-packages\borb-2.0.26-py3.9.egg\borb\io\read\reference\reference_transformer.py:105, in ReferenceTransformer.transform(self, object_to_transform, parent_object, context, event_listeners)
    103 assert referenced_object is not None
    104 context.indirect_reference_chain.add(object_to_transform)
--> 105 transformed_referenced_object = self.get_root_transformer().transform(
    106     referenced_object, parent_object, context, event_listeners
    107 )
    108 context.indirect_reference_chain.remove(object_to_transform)
    110 # update cache

File c:\users\python\sites\pdf\venv\lib\site-packages\borb-2.0.26-py3.9.egg\borb\io\read\any_object_transformer.py:100, in AnyObjectTransformer.transform(self, object_to_transform, parent_object, context, event_listeners)
     93     return super().transform(
     94         object_to_transform,
     95         parent_object,
     96         ReadTransformerState(),
     97         event_listeners,
     98     )
     99 else:
--> 100     return super().transform(
    101         object_to_transform, parent_object, context, event_listeners
    102     )

File c:\users\python\sites\pdf\venv\lib\site-packages\borb-2.0.26-py3.9.egg\borb\io\read\transformer.py:123, in Transformer.transform(self, object_to_transform, parent_object, context, event_listeners)
    121 self._level += 1
    122 self._invocation_count += 1
--> 123 out = h.transform(
    124     object_to_transform,
    125     parent_object=parent_object,
    126     context=context,
    127     event_listeners=event_listeners,
    128 )
    129 self._level -= 1
    130 # print("%s</%s>" % ("   " * self.level, h.__class__.__name__))

File c:\users\python\sites\pdf\venv\lib\site-packages\borb-2.0.26-py3.9.egg\borb\io\read\page\root_dictionary_transformer.py:86, in RootDictionaryTransformer.transform(self, object_to_transform, parent_object, context, event_listeners)
     84 for t in self.get_root_transformer().get_children():
     85     if isinstance(t, DictionaryTransformer):
---> 86         transformed_root_dictionary = t.transform(
     87             object_to_transform, parent_object, context, event_listeners
     88         )
     89         break
     91 assert transformed_root_dictionary is not None

File c:\users\python\sites\pdf\venv\lib\site-packages\borb-2.0.26-py3.9.egg\borb\io\read\object\dictionary_transformer.py:48, in DictionaryTransformer.transform(self, object_to_transform, parent_object, context, event_listeners)
     46 # transform key/value pair(s)
     47 for k, v in object_to_transform.items():
---> 48     v = self.get_root_transformer().transform(
     49         v, object_to_transform, context, event_listeners
     50     )
     51     if v is not None:
     52         object_to_transform[k] = v

File c:\users\python\sites\pdf\venv\lib\site-packages\borb-2.0.26-py3.9.egg\borb\io\read\any_object_transformer.py:100, in AnyObjectTransformer.transform(self, object_to_transform, parent_object, context, event_listeners)
     93     return super().transform(
     94         object_to_transform,
     95         parent_object,
     96         ReadTransformerState(),
     97         event_listeners,
     98     )
     99 else:
--> 100     return super().transform(
    101         object_to_transform, parent_object, context, event_listeners
    102     )

File c:\users\python\sites\pdf\venv\lib\site-packages\borb-2.0.26-py3.9.egg\borb\io\read\transformer.py:123, in Transformer.transform(self, object_to_transform, parent_object, context, event_listeners)
    121 self._level += 1
    122 self._invocation_count += 1
--> 123 out = h.transform(
    124     object_to_transform,
    125     parent_object=parent_object,
    126     context=context,
    127     event_listeners=event_listeners,
    128 )
    129 self._level -= 1
    130 # print("%s</%s>" % ("   " * self.level, h.__class__.__name__))

File c:\users\python\sites\pdf\venv\lib\site-packages\borb-2.0.26-py3.9.egg\borb\io\read\reference\reference_transformer.py:105, in ReferenceTransformer.transform(self, object_to_transform, parent_object, context, event_listeners)
    103 assert referenced_object is not None
    104 context.indirect_reference_chain.add(object_to_transform)
--> 105 transformed_referenced_object = self.get_root_transformer().transform(
    106     referenced_object, parent_object, context, event_listeners
    107 )
    108 context.indirect_reference_chain.remove(object_to_transform)
    110 # update cache

File c:\users\python\sites\pdf\venv\lib\site-packages\borb-2.0.26-py3.9.egg\borb\io\read\any_object_transformer.py:100, in AnyObjectTransformer.transform(self, object_to_transform, parent_object, context, event_listeners)
     93     return super().transform(
     94         object_to_transform,
     95         parent_object,
     96         ReadTransformerState(),
     97         event_listeners,
     98     )
     99 else:
--> 100     return super().transform(
    101         object_to_transform, parent_object, context, event_listeners
    102     )

File c:\users\python\sites\pdf\venv\lib\site-packages\borb-2.0.26-py3.9.egg\borb\io\read\transformer.py:123, in Transformer.transform(self, object_to_transform, parent_object, context, event_listeners)
    121 self._level += 1
    122 self._invocation_count += 1
--> 123 out = h.transform(
    124     object_to_transform,
    125     parent_object=parent_object,
    126     context=context,
    127     event_listeners=event_listeners,
    128 )
    129 self._level -= 1
    130 # print("%s</%s>" % ("   " * self.level, h.__class__.__name__))

File c:\users\python\sites\pdf\venv\lib\site-packages\borb-2.0.26-py3.9.egg\borb\io\read\object\dictionary_transformer.py:48, in DictionaryTransformer.transform(self, object_to_transform, parent_object, context, event_listeners)
     46 # transform key/value pair(s)
     47 for k, v in object_to_transform.items():
---> 48     v = self.get_root_transformer().transform(
     49         v, object_to_transform, context, event_listeners
     50     )
     51     if v is not None:
     52         object_to_transform[k] = v

File c:\users\python\sites\pdf\venv\lib\site-packages\borb-2.0.26-py3.9.egg\borb\io\read\any_object_transformer.py:100, in AnyObjectTransformer.transform(self, object_to_transform, parent_object, context, event_listeners)
     93     return super().transform(
     94         object_to_transform,
     95         parent_object,
     96         ReadTransformerState(),
     97         event_listeners,
     98     )
     99 else:
--> 100     return super().transform(
    101         object_to_transform, parent_object, context, event_listeners
    102     )

File c:\users\python\sites\pdf\venv\lib\site-packages\borb-2.0.26-py3.9.egg\borb\io\read\transformer.py:123, in Transformer.transform(self, object_to_transform, parent_object, context, event_listeners)
    121 self._level += 1
    122 self._invocation_count += 1
--> 123 out = h.transform(
    124     object_to_transform,
    125     parent_object=parent_object,
    126     context=context,
    127     event_listeners=event_listeners,
    128 )
    129 self._level -= 1
    130 # print("%s</%s>" % ("   " * self.level, h.__class__.__name__))

File c:\users\python\sites\pdf\venv\lib\site-packages\borb-2.0.26-py3.9.egg\borb\io\read\object\array_transformer.py:48, in ArrayTransformer.transform(self, object_to_transform, parent_object, context, event_listeners)
     46 # transform child(ren)
     47 for i in range(0, len(object_to_transform)):
---> 48     object_to_transform[i] = self.get_root_transformer().transform(
     49         object_to_transform[i], object_to_transform, context, event_listeners
     50     )
     52 # return
     53 return object_to_transform

File c:\users\python\sites\pdf\venv\lib\site-packages\borb-2.0.26-py3.9.egg\borb\io\read\any_object_transformer.py:100, in AnyObjectTransformer.transform(self, object_to_transform, parent_object, context, event_listeners)
     93     return super().transform(
     94         object_to_transform,
     95         parent_object,
     96         ReadTransformerState(),
     97         event_listeners,
     98     )
     99 else:
--> 100     return super().transform(
    101         object_to_transform, parent_object, context, event_listeners
    102     )

File c:\users\python\sites\pdf\venv\lib\site-packages\borb-2.0.26-py3.9.egg\borb\io\read\transformer.py:123, in Transformer.transform(self, object_to_transform, parent_object, context, event_listeners)
    121 self._level += 1
    122 self._invocation_count += 1
--> 123 out = h.transform(
    124     object_to_transform,
    125     parent_object=parent_object,
    126     context=context,
    127     event_listeners=event_listeners,
    128 )
    129 self._level -= 1
    130 # print("%s</%s>" % ("   " * self.level, h.__class__.__name__))

File c:\users\python\sites\pdf\venv\lib\site-packages\borb-2.0.26-py3.9.egg\borb\io\read\reference\reference_transformer.py:105, in ReferenceTransformer.transform(self, object_to_transform, parent_object, context, event_listeners)
    103 assert referenced_object is not None
    104 context.indirect_reference_chain.add(object_to_transform)
--> 105 transformed_referenced_object = self.get_root_transformer().transform(
    106     referenced_object, parent_object, context, event_listeners
    107 )
    108 context.indirect_reference_chain.remove(object_to_transform)
    110 # update cache

File c:\users\python\sites\pdf\venv\lib\site-packages\borb-2.0.26-py3.9.egg\borb\io\read\any_object_transformer.py:100, in AnyObjectTransformer.transform(self, object_to_transform, parent_object, context, event_listeners)
     93     return super().transform(
     94         object_to_transform,
     95         parent_object,
     96         ReadTransformerState(),
     97         event_listeners,
     98     )
     99 else:
--> 100     return super().transform(
    101         object_to_transform, parent_object, context, event_listeners
    102     )

File c:\users\python\sites\pdf\venv\lib\site-packages\borb-2.0.26-py3.9.egg\borb\io\read\transformer.py:123, in Transformer.transform(self, object_to_transform, parent_object, context, event_listeners)
    121 self._level += 1
    122 self._invocation_count += 1
--> 123 out = h.transform(
    124     object_to_transform,
    125     parent_object=parent_object,
    126     context=context,
    127     event_listeners=event_listeners,
    128 )
    129 self._level -= 1
    130 # print("%s</%s>" % ("   " * self.level, h.__class__.__name__))

File c:\users\python\sites\pdf\venv\lib\site-packages\borb-2.0.26-py3.9.egg\borb\io\read\page\page_dictionary_transformer.py:64, in PageDictionaryTransformer.transform(self, object_to_transform, parent_object, context, event_listeners)
     62 if k == "Parent":
     63     continue
---> 64 v = self.get_root_transformer().transform(
     65     v, page_out, context, event_listeners
     66 )
     67 if v is not None:
     68     page_out[k] = v

File c:\users\python\sites\pdf\venv\lib\site-packages\borb-2.0.26-py3.9.egg\borb\io\read\any_object_transformer.py:100, in AnyObjectTransformer.transform(self, object_to_transform, parent_object, context, event_listeners)
     93     return super().transform(
     94         object_to_transform,
     95         parent_object,
     96         ReadTransformerState(),
     97         event_listeners,
     98     )
     99 else:
--> 100     return super().transform(
    101         object_to_transform, parent_object, context, event_listeners
    102     )

File c:\users\python\sites\pdf\venv\lib\site-packages\borb-2.0.26-py3.9.egg\borb\io\read\transformer.py:123, in Transformer.transform(self, object_to_transform, parent_object, context, event_listeners)
    121 self._level += 1
    122 self._invocation_count += 1
--> 123 out = h.transform(
    124     object_to_transform,
    125     parent_object=parent_object,
    126     context=context,
    127     event_listeners=event_listeners,
    128 )
    129 self._level -= 1
    130 # print("%s</%s>" % ("   " * self.level, h.__class__.__name__))

File c:\users\python\sites\pdf\venv\lib\site-packages\borb-2.0.26-py3.9.egg\borb\io\read\object\dictionary_transformer.py:48, in DictionaryTransformer.transform(self, object_to_transform, parent_object, context, event_listeners)
     46 # transform key/value pair(s)
     47 for k, v in object_to_transform.items():
---> 48     v = self.get_root_transformer().transform(
     49         v, object_to_transform, context, event_listeners
     50     )
     51     if v is not None:
     52         object_to_transform[k] = v

File c:\users\python\sites\pdf\venv\lib\site-packages\borb-2.0.26-py3.9.egg\borb\io\read\any_object_transformer.py:100, in AnyObjectTransformer.transform(self, object_to_transform, parent_object, context, event_listeners)
     93     return super().transform(
     94         object_to_transform,
     95         parent_object,
     96         ReadTransformerState(),
     97         event_listeners,
     98     )
     99 else:
--> 100     return super().transform(
    101         object_to_transform, parent_object, context, event_listeners
    102     )

File c:\users\python\sites\pdf\venv\lib\site-packages\borb-2.0.26-py3.9.egg\borb\io\read\transformer.py:123, in Transformer.transform(self, object_to_transform, parent_object, context, event_listeners)
    121 self._level += 1
    122 self._invocation_count += 1
--> 123 out = h.transform(
    124     object_to_transform,
    125     parent_object=parent_object,
    126     context=context,
    127     event_listeners=event_listeners,
    128 )
    129 self._level -= 1
    130 # print("%s</%s>" % ("   " * self.level, h.__class__.__name__))

File c:\users\python\sites\pdf\venv\lib\site-packages\borb-2.0.26-py3.9.egg\borb\io\read\object\dictionary_transformer.py:48, in DictionaryTransformer.transform(self, object_to_transform, parent_object, context, event_listeners)
     46 # transform key/value pair(s)
     47 for k, v in object_to_transform.items():
---> 48     v = self.get_root_transformer().transform(
     49         v, object_to_transform, context, event_listeners
     50     )
     51     if v is not None:
     52         object_to_transform[k] = v

    [... skipping similar frames: AnyObjectTransformer.transform at line 100 (1 times), Transformer.transform at line 123 (1 times)]

File c:\users\python\sites\pdf\venv\lib\site-packages\borb-2.0.26-py3.9.egg\borb\io\read\reference\reference_transformer.py:105, in ReferenceTransformer.transform(self, object_to_transform, parent_object, context, event_listeners)
    103 assert referenced_object is not None
    104 context.indirect_reference_chain.add(object_to_transform)
--> 105 transformed_referenced_object = self.get_root_transformer().transform(
    106     referenced_object, parent_object, context, event_listeners
    107 )
    108 context.indirect_reference_chain.remove(object_to_transform)
    110 # update cache

File c:\users\python\sites\pdf\venv\lib\site-packages\borb-2.0.26-py3.9.egg\borb\io\read\any_object_transformer.py:100, in AnyObjectTransformer.transform(self, object_to_transform, parent_object, context, event_listeners)
     93     return super().transform(
     94         object_to_transform,
     95         parent_object,
     96         ReadTransformerState(),
     97         event_listeners,
     98     )
     99 else:
--> 100     return super().transform(
    101         object_to_transform, parent_object, context, event_listeners
    102     )

File c:\users\python\sites\pdf\venv\lib\site-packages\borb-2.0.26-py3.9.egg\borb\io\read\transformer.py:123, in Transformer.transform(self, object_to_transform, parent_object, context, event_listeners)
    121 self._level += 1
    122 self._invocation_count += 1
--> 123 out = h.transform(
    124     object_to_transform,
    125     parent_object=parent_object,
    126     context=context,
    127     event_listeners=event_listeners,
    128 )
    129 self._level -= 1
    130 # print("%s</%s>" % ("   " * self.level, h.__class__.__name__))

File c:\users\python\sites\pdf\venv\lib\site-packages\borb-2.0.26-py3.9.egg\borb\io\read\object\stream_transformer.py:55, in StreamTransformer.transform(self, object_to_transform, parent_object, context, event_listeners)
     52         object_to_transform[k] = v
     54 # apply filter(s)
---> 55 object_to_transform = decode_stream(object_to_transform)
     57 # convert (remainder of) stream dictionary
     58 for k, v in object_to_transform.items():

File c:\users\python\sites\pdf\venv\lib\site-packages\borb-2.0.26-py3.9.egg\borb\io\filter\stream_decode_util.py:74, in decode_stream(s)
     72 # RunLengthDecode
     73 if filter_name in ["RunLengthDecode"]:
---> 74     transformed_bytes = RunLengthDecode.decode(transformed_bytes)
     75     continue
     77 # unknown filter

File c:\users\python\sites\pdf\venv\lib\site-packages\borb-2.0.26-py3.9.egg\borb\io\filter\run_length_decode.py:34, in RunLengthDecode.decode(bytes_in)
     32 for i in range(0, len(bytes_in), 2):
     33     b = bytes_in[i]
---> 34     n = bytes_in[i + 1]
     35     for j in range(0, n):
     36         bytes_out.append(b)

IndexError: index out of range

**Desktop (please complete the following information):**
 - OS: Windows 10
 - borb version 2.0.26
 - Python 3.9.5
- input PDF: I tried 3 different PDF's from 2 different suppliers. See attachments for one of them

Here is the invoice. I blocked out the recipients address from privacy reasons. The invoice generates the error above with or without the address blocked out.

[output.pdf](https://github.com/jorisschellekens/borb/files/8806197/output.pdf)

**Comment by jorisschellekens** [comment]
Hi @remar1972 ,

Your bug is actually quite straightforward. Your PDF uses run-length-encoding. This is a compression algorithm.

The pseudo-code for that is:
1. Go over the input in groups of 2 bytes
2. repeat the first byte of the group (of 2) as many times as the last byte of the group indicates

So something like `A588` would decompress to `AAAAA88888888`.
The main requirement is that the number of bytes in the input are even.
And that is why your document fails. It is trying to use this decompression algorithm on an input that contains an odd number of bytes.

I'll have a look at what other libraries do in this particular case.

Kind regards,
Joris Schellekens

**Comment by jorisschellekens** [comment]
My bad.

Turns out RLE in PDF is different.

> The RunLengthDecode filter decodes data that has been encoded in a simple byte-oriented format based on
run length. The encoded data shall be a sequence of runs, where each run shall consist of a length byte
followed by 1 to 128 bytes of data. If the length byte is in the range 0 to 127, the following length + 1 (1 to 128)
bytes shall be copied literally during decompression. If length is in the range 129 to 255, the following single
byte shall be copied 257 - length (2 to 128) times during decompression. A length value of 128 shall denote
EOD.

I'm going to implement this and see how that goes.

**Comment by remar1972** [comment]
much appreciated!

**Comment by jorisschellekens** [comment]
Turns out it does not (negatively) impact the accuracy of text extraction.
So I'm happy to include this in the next release.

Kind regards,
Joris Schellekens

**Comment by remar1972** [comment]
Thanks for the update, works like a charm!
