### ISSUE TITLE
BUG : Document.get_document_info().get_file_size() raises TypeError: 'Document' object is not callable

### ISSUE THREAD

**Issue by metalogueur** [jorisschellekens/borb#106]
**Describe the bug**

Trying to get the document's file size using the ```get_file_size()``` method raises a _TypeError: 'Document' object not callable_ error.

In the ```DocumentInfo``` class, all meta-information is returned from the ```Document``` dictionary, except for the file size, which is returned as such (see line 130):

```return int(self._document("FileSize"))```

**Minimal working example**
```
from pathlib import Path
from borb.pdf import (Document, PDF)
from borb.pdf.trailer.document_info import DocumentInfo

BASE_DIR = Path(__file__).resolve().parent
pdf_file = BASE_DIR / 'some_file.pdf'

with open(pdf_file, 'rb') as f:
    document = PDF.loads(f)

trailer = document.get_document_info()
print(trailer.get_file_size())    # throws the TypeError
```

**Expected behaviour**

Parentheses should be replaced by square brackets:

```return int(self._document["FileSize"])```

**Desktop (please complete the following information):**
 - OS: Win 10
 - Python 3.10
 - borb version 2.0.26

**Comment by jorisschellekens** [comment]
Fixed.

Turns out that method called `document('FileSize')` which is of course the wrong syntax to get something out of a `dict`.
I changed it to `document['FileSize']` which works.

Kind regards,
Joris Schellekens
