### ISSUE TITLE
circular import

### ISSUE THREAD

**Issue by zhu1205** [jorisschellekens/borb#109]
**Describe the bug**
ImportError: circular import

**To Reproduce**
Steps to reproduce the behaviour: 
Python version: 3.8.10
1. create a python unit
2. import borb.toolkit.ocr.ocr_as_optional_content_group
3. debug or run the unit.

```python code```
from borb.toolkit.ocr.ocr_as_optional_content_group import OCRAsOptionalContentGroup

def main():
    print("do nothing")

if __name__ == "__main__":
    main()

**Expected behaviour**
Import module without error.

**Screenshots**
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/work/program/python/venv/test/lib/python3.8/site-packages/borb/toolkit/ocr/ocr_as_optional_content_group.py", line 15, in <module>
    from borb.io.read.reference.xref_transformer import EndDocumentEvent
  File "/home/work/program/python/venv/test/lib/python3.8/site-packages/borb/io/read/reference/xref_transformer.py", line 15, in <module>
    from borb.io.read.transformer import ReadTransformerState, Transformer
  File "/home/work/program/python/venv/test/lib/python3.8/site-packages/borb/io/read/transformer.py", line 14, in <module>
    from borb.pdf.canvas.event.event_listener import EventListener
  File "**/home/work/program/python/venv/test/lib/python3.8/site-packages/borb/pdf/\_\_init\_\_.py**", line 48, in <module>
    from .pdf import PDF
  File "/home/work/program/python/venv/test/lib/python3.8/site-packages/borb/pdf/pdf.py", line 15, in <module>
    from borb.io.read.any_object_transformer import (
  File "/home/work/program/python/venv/test/lib/python3.8/site-packages/borb/io/read/any_object_transformer.py", line 12, in <module>
    from borb.io.read.font.font_dictionary_transformer import FontDictionaryTransformer
  File "/home/work/program/python/venv/test/lib/python3.8/site-packages/borb/io/read/font/font_dictionary_transformer.py", line 11, in <module>
    from borb.io.read.transformer import ReadTransformerState, Transformer
ImportError: cannot import name 'ReadTransformerState' from partially initialized module 'borb.io.read.transformer' (most likely due to a circular import) (/home/work/program/python/venv/test/lib/python3.8/site-packages/borb/io/read/transformer.py)
python-BaseException

**Desktop (please complete the following information):**
ubuntu 20.04

**Additional context**
This caused by package or module import for type hints. 
If there's a \_\_init\_\_.py in a package, importing module from package will implicitly execute \_\_init\_\_.py.
reference:
https://docs.python.org/3/reference/import.html#regular-packages
https://realpython.com/lessons/package-initialization/

Thankfully, there’s a trick to add circular imports for type hints without causing:
https://adamj.eu/tech/2021/05/13/python-type-hints-how-to-fix-circular-imports/

**Comment by jorisschellekens** [comment]
I'm not really great at this whole circular import thing.
Do you have a suggested fix?

**Comment by xD34THROW** [comment]
Taking a look at this one now to see if it has to do with the type checking. Give me a bit, it's my first real PR.

**Comment by xD34THROW** [comment]
After manually going through the dependencies, I _believe_ that this stems from `EventListener`'s parent module's `__init__.py` calling a series of imports that ends at `io.read.transformer.ReadTransformerState`. Changing this as per [this link](https://adamj.eu/tech/2021/05/13/python-type-hints-how-to-fix-circular-imports/) led to an issue with `XREFTransformer`. I'm going through the import chain now to try to fix this.

**Comment by jorisschellekens** [comment]
I am obviously not going to accept the PR if it does not completely solve the issue.

Kind regards,
Joris Schellekens

**Comment by zhu1205** [comment]
I just empty borb.pdf.__init__.py to solve the issue, but I don't know whether it will cause some other issue.

**Comment by jorisschellekens** [comment]
Fixed.

I changed the imports in `ocr_as_optional_content_group` to be the following:

```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
    This class adds performs OCR and adds recognized text in an optional content group on the PDF.
    This enables the user to have a searchable PDF, whilst being able to turn on/off OCR features.
"""
# FIX: circular imports (1)
from __future__ import annotations
import datetime
import typing
import zlib
from decimal import Decimal
from pathlib import Path

from borb.datastructure.disjoint_set import disjointset
from borb.io.read.types import Decimal as bDecimal
from borb.io.read.types import Dictionary, List, Name, String
from borb.pdf.canvas.event.event_listener import Event
from borb.pdf.canvas.geometry.rectangle import Rectangle
from borb.pdf.canvas.layout.text.chunk_of_text import ChunkOfText
from borb.pdf.document.document import Document
from borb.pdf.page.page import Page
from borb.toolkit.ocr.ocr_image_render_event_listener import (
    OCREvent,
    OCRImageRenderEventListener,
)

# FIX: circular imports (2)
from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from borb.io.read.reference.xref_transformer import EndDocumentEvent

```

I built it, installed the `whl` in a separate project, and it worked.
You can expect this fix in the next release.
