### ISSUE TITLE
Textfield value overwrites all

### ISSUE THREAD

**Issue by wenestam** [jorisschellekens/borb#112]
Hello! Just discovered this awesome library today.

I'm interested in the forms feature. I have the same issue as one commented on this post, long time ago:

https://stackabuse.com/creating-a-form-in-a-pdf-document-in-python-with-borb/

Comment: "Thank you very much. Awesome tutorial.
Just one little note, you have used the values "Doe" and "John" as for the name and surname and in the output pdf, the values appeared "John" as for both name and surname, and when click in the name field "Doe" appeared"

Likewise, when I try to structure my forms with a pre-filled value, the last value of the table overwrites other, until you actively click into the textbox. 

Is there any way to avoid this? Some of the source code I can comment out?

Example code to recreate the problem:

```python

  def main():

      # create Document
      doc: Document = Document()
  
      # create Page
      page: Page = Page()
  
      # add Page to Document
      doc.append_page(page)
  
      # set a PageLayout
      layout: PageLayout =SingleColumnLayout(page)
  
  
      layout.add(Paragraph("Your information", font_color=HexColor("150549"), font_size=Decimal(15)))
  
      layout.add(Paragraph("Kontaktinformationen:", font="Helvetica-Bold"))
  
     
      # Use a table to lay out the form
      table: FixedColumnWidthTable = FixedColumnWidthTable(number_of_rows=6, number_of_columns=2)
  
  
      # Name
      table.add(Paragraph("Name, Vorname : ", horizontal_alignment=Alignment.RIGHT, font_color=HexColor("050100")))
      table.add(TextField(value="Random 1 ", font_color=HexColor("050100"), font_size=Decimal(20)))
  
      # Surname
      table.add(Paragraph("Familienname : ", horizontal_alignment=Alignment.RIGHT, font_color=HexColor("050100")))
      table.add(TextField(value="Random 2", font_color=HexColor("050100"), font_size=Decimal(20)))
      
      # Name before marraige
      table.add(Paragraph("Geburtsname : ", horizontal_alignment=Alignment.RIGHT, font_color=HexColor("050100")))
      table.add(TextField(value="Random 3 ", font_color=HexColor("050100"), font_size=Decimal(20)))
  
      # Straße
      table.add(Paragraph("Straße : ", horizontal_alignment=Alignment.RIGHT, font_color=HexColor("050100")))
      table.add(TextField(value="Random 4", font_color=HexColor("050100"), font_size=Decimal(20)))
  
      # PLZ
      table.add(Paragraph("PLZ, Wohnort (bei Wehrpflichtigen Standort) : ", horizontal_alignment=Alignment.RIGHT, font_color=HexColor("050100")))
      table.add(TextField(value="Random 5", font_color=HexColor("050100"), font_size=Decimal(20)))
  
      # Birthday
      table.add(Paragraph("Geburtsdatum : ", horizontal_alignment=Alignment.RIGHT, font_color=HexColor("050100")))
      table.add(TextField(value="Random 6 ", font_color=HexColor("050100"), font_size=Decimal(20)))
  
      table.set_padding_on_all_cells(Decimal(5), Decimal(5), Decimal(5), Decimal(5))
      table.no_borders()
  
      layout.add(table)
  
      with open("output.pdf", "wb") as pdf_file_handle:
          PDF.dumps(pdf_file_handle, doc)


  if __name__ == "__main__":
      main()

```

Kind regards

**Comment by jorisschellekens** [comment]
I remember a similar issue appearing in the repo (or perhaps I am mistaken, or perhaps it was the examples repo).
Can you try opening the PDF in another reader? I think that was the conclusion last time, that Adobe is acting up.

**Comment by wenestam** [comment]
Hi, thanks for the fast reply!

After trying the following pdf readers, the issue remains the same.

Adobe Acrobat Reader
Foxit Reader
Microsoft edge
Chrome
Firefox

This would be a really cool feature if it worked. Do you think there is anywhere in the code where I can overwrite this code?

Also, how does a Textfield in the forms go from open for edit to closed? Currently if I open up a document and save it, next time I open it I can edit it again. Is there any possibility to, that after one save, this Textfield is locked?

Kind regards

**Comment by A-rad** [comment]
Hi @jorisschellekens, 

Thank you for the quick response!  I've been coding for years now but only started actively participating in the community this year.

Please find attached is the "Testfile2.pdf".  

Below is the code that generated it:
`#!/usr/bin/env python3
from pathlib import Path
import typing
from borb.pdf.document.document import Document
from borb.pdf.canvas.layout.page_layout.multi_column_layout import SingleColumnLayout
from borb.pdf.canvas.layout.text.paragraph import Paragraph
from borb.pdf.pdf import PDF
from borb.pdf.canvas.layout.page_layout.page_layout import PageLayout
from landscapeTable import FixedColumnWidthTable
from borb.pdf.canvas.layout.forms.text_field import TextField
from landscapePage import LPage
from borb.pdf.page.page import Page
from decimal import Decimal

#  Color for green is #E2EFDA
#  Color for grey is #D0CECE
def main():
    pdf: Document = Document()

    # Create empty Page
    page: Page = Page()
    # Add Page to Document
    pdf.add_page(page)


    # Create PageLayout
    layout: PageLayout = SingleColumnLayout(page)
    layout.add(
        FixedColumnWidthTable(number_of_rows=4, number_of_columns=3)
        .add(Paragraph("Sometitle:"))
        .add(TextField(field_name="someFieldName", value="one"))
        .add(Paragraph("Blank"))
        .add(Paragraph("Sometitle2:"))
        .add(TextField(field_name="someotherfield", value="two"))
        .add(Paragraph("Blank2:"))
        .add(Paragraph("Sometitle3:"))
        .add(TextField(field_name="another", value="three"))
        .set_padding_on_all_cells(Decimal(2), Decimal(2), Decimal(2), Decimal(2))
        .no_borders()
  
    )
  

    with open("Testfile2.pdf", "wb") as pdf_file_handle:
        PDF.dumps(pdf_file_handle, pdf)
    
if __name__ == "__main__":
    main()`

I am not familiar with using vera pdf.  Could you please elaborate?  


[Testfile2.pdf](https://github.com/jorisschellekens/borb/files/9133588/Testfile2.pdf)

**Comment by jorisschellekens** [comment]
This example isn't minimal yet. You probably don't need the table or paragraphs.

Once you've made those adjustments I'll help you out with Vera pdf.

**Comment by jorisschellekens** [comment]
```python
from pathlib import Path
import typing
from borb.pdf.document.document import Document
from borb.pdf.canvas.layout.page_layout.multi_column_layout import SingleColumnLayout
from borb.pdf.pdf import PDF
from borb.pdf.canvas.layout.page_layout.page_layout import PageLayout
from borb.pdf.canvas.layout.forms.text_field import TextField
from borb.pdf.page.page import Page
from decimal import Decimal

def main():
    pdf: Document = Document()

    # Create empty Page
    page: Page = Page()

    # Add Page to Document
    pdf.add_page(page)

    # Create PageLayout
    layout: PageLayout = SingleColumnLayout(page)
    layout.add(TextField(field_name="someFieldName", value="one"))
    layout.add(TextField(field_name="someotherfield", value="two"))
  
    with open("Testfile2.pdf", "wb") as pdf_file_handle:
        PDF.dumps(pdf_file_handle, pdf)
    
if __name__ == "__main__":
    main()`
```

**Comment by A-rad** [comment]
@jorisschellekens, Thank you!  I really appreciate your help.

Using the code above, here is file it created.

[Testfile2.pdf](https://github.com/jorisschellekens/borb/files/9133920/Testfile2.pdf)
d

**Comment by jorisschellekens** [comment]
Can you try this document?
Same behaviour

[minimal_textfield_example.pdf](https://github.com/jorisschellekens/borb/files/9133969/minimal_textfield_example.pdf)

**Comment by A-rad** [comment]
This document does not have the same behaviour.  I can save entered values, close the pdf, open it, and the values I have entered are still there.  Nothing is overwritten. 

My document has the issue and yours does not.  Is this because I am not using vera pdf?

**Comment by jorisschellekens** [comment]
No, vera PDF is an online tool that validates PDF documents. It can show you whether a PDF is valid or not.
I modified the PDF I sent to you, hence it being correct. I think I understand what is going wrong.

**Comment by jorisschellekens** [comment]
Final check:
Can you verify whether this file works as expected?

[minimal_textfield_example.pdf](https://github.com/jorisschellekens/borb/files/9134237/minimal_textfield_example.pdf)

**Comment by A-rad** [comment]
Yes.  I can confirm this file also works as expected.

What was the issue?

**Comment by jorisschellekens** [comment]
You're going to need to know a lot about PDF syntax to understand the issue here.
But let's give it a try :-)

PDF consists of primitive types, dictionaries, lists and binary data.

The `TextField` you see is actually represented as (if you opened the PDF in something like notepad):

```
12 0 obj
<</Type /Annot /Subtype /Widget /F 4 /Rect [59.50 733.80 535.50 745.80] /FT /Tx /P 1 0 R /T (someotherfield) /V (two) /DV () /DR 7 0 R /DA (0.000000 0.000000 0.000000 rg /F1 12.000000 Tf) /AP 15 0 R>>
endobj

15 0 obj
<</N 14 0 R>>
endobj

14 0 obj
<</Type /XObject /Subtype /Form /BBox [0 0 476.00 12] /Resources 7 0 R /Filter /FlateDecode /Length 19>>
stream
x\DA\D3\A9Pp\F2uVp\F5u\00\A7\E3
endstream
endobj
```

`12 0 obj` is PDF syntax to say "object 12, revision 0 starts here". (Object 12 is the `TextField` by the way.)
Object 12 is a dictionary (you can tell by the `<<` and `>>`), it consists of keys followed by their value.

One of the keys of object 12 is `/AP`, it's value is `15 0 R` (this is PDF syntax for "a reference to object 15")
`/AP` stands for **appearance**. This key/value pair tells the PDF reader how to render the content in the `TextField`.

Fields can have multiple appearances:
- when selected
- when "on"
- when "off"
- "normal"
- etc

That's why object 15 is another dictionary. 
It tells the PDF reader the `/N` (normal) appearance of the `TextField` is `14 0 R`.

This is where the problem was. `borb` does some clever compression here. It stores the hash value of each object, and attempts to re-use objects as much as possible.

So with 2 `TextField` objects, their appearance was the same, and the optimization kicked in. They both contained a reference to the same object. To be clear, this is not against the spec. But the behaviour is undefined.

I added a method to all (primitive and composite) PDF types `set_is_unique` which allowed me to bypass the optimization.

I'm going to include this fix in the next release.

Kind regards,
Joris Schellekens

**Comment by A-rad** [comment]
@jorisschellekens  Thank you!  That makes a lot of sense from what I was observing.  

I am not familiar with pdf syntax, but I can understand what you are saying.  I have tried a few different libraries for creating pdfs and this is by far my favoirte!  I look forward to the new release.
