### ISSUE TITLE
Use `defusedxml` instead of `xml.etree`

### ISSUE THREAD

**Issue by KOLANICH** [jorisschellekens/borb#115]
**Describe the bug**
`xml.etree` is subject to "million laughs" attack.

**Comment by jorisschellekens** [comment]
I'd love to find a library that is a bit better supported.
`defusedxml` only has 280 stars on GitHub. It was last updated 9 months ago.
I am not going to add a dependency (replacing something that is part of the standard) if `defusedxml` itself is not even regularly updated.
