### ISSUE TITLE
Large bundled resources should be moved into separate packages.

### ISSUE THREAD

**Issue by KOLANICH** [jorisschellekens/borb#116]
**Is your feature request related to a problem? Please describe.**
I don't need them.

**Describe the solution you'd like**
Their installation made optional.

**Comment by KOLANICH** [comment]
I suggest to create separate packages for them and add them into optional dependencies. Also make them universal enough to encourage their reuse by other packages. I have seen quite some packages that bundle resources too, causing absolutely unnecessary bloat.

**Comment by jorisschellekens** [comment]
Fixed

**Comment by KOLANICH** [comment]
Thanks.
