### ISSUE TITLE
Tests should never end up within a wheel.

### ISSUE THREAD

**Issue by KOLANICH** [jorisschellekens/borb#117]
**Describe the bug**
Tests are archived into the wheel by mistake.

**To Reproduce**
Steps to reproduce the behaviour:

```bash
python3 -m build wheel
```

**Expected behaviour**
No tests in the wheel.

**Comment by jorisschellekens** [comment]
Do you have a suggested solution?
I'm not an expert on Python packaging.
And I've been trying a few things with both `MANIFEST.in` and `setup.py` but nothing seems to work properly.

**Comment by KOLANICH** [comment]
`find_packages` should be used with `include=["borb", "borb.*"]`, I guess.

>`python3 -m build wheel`

oops, should look like `python3 -m build -nwx`.

**Comment by jorisschellekens** [comment]
Fixed

**Comment by KOLANICH** [comment]
Thanks.
