### ISSUE TITLE
I have two questions 

### ISSUE THREAD

**Issue by blako99** [jorisschellekens/borb#118]
Hello everyone!

Thanks very much for creating borb, Joris, is an amazing library!

But i would like to know how to do the next two things : 

-Creating two tables and place them at the same height I mean, one next to the other one.

-Establish an specific height to have all the elements in one single pdf page 

Thanks very much guys

**Comment by jorisschellekens** [comment]
Hi there,

To place two tables next to eachother, you have 3 (easy) options.
1. Use a `MultiColumnLayout` to divide the `Page` in 2 (or more) columns. You can then put one `Table` in each column.
2. You can use the absolute layout mechanism. Each `LayoutElement` (and `Table` inherits from `LayoutElement`) has a method `layout` which accepts a `Rectangle` and a `Page`. You can use these methods and simply pass 2 adjacent rectangles. 
3. You can cheat and build 1 `Table` in stead of 2. Then simply remove the border of some `TableCell` objects to give the illusion of 2 separate tables.
