### ISSUE TITLE
Save PDF using Dropbox API

### ISSUE THREAD

**Issue by IAyala** [jorisschellekens/borb#119]
I am saving pdfs created programatically using borb in my machine (thank you for the library, it is great!!). But I would like to be able to save the pdf directly into my dropbox account

I tried the following:

```python
dbx.files_upload(pdf_object.pdf, '/my_file_from_borb.pdf',dropbox.files.WriteMode.add)
```

But got this error:

```text
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/vscode/.local/lib/python3.10/site-packages/dropbox/base.py", line 3207, in files_upload
    r = self.request(
  File "/home/vscode/.local/lib/python3.10/site-packages/dropbox/dropbox_client.py", line 323, in request
    res = self.request_json_string_with_retry(host,
  File "/home/vscode/.local/lib/python3.10/site-packages/dropbox/dropbox_client.py", line 473, in request_json_string_with_retry
    return self.request_json_string(host,
  File "/home/vscode/.local/lib/python3.10/site-packages/dropbox/dropbox_client.py", line 535, in request_json_string
    raise TypeError('expected request_binary as binary type, got %s' %
TypeError: expected request_binary as binary type, got <class 'borb.pdf.document.Document'>
```
Is there a way to make this work?

Thank you!

**Comment by jorisschellekens** [comment]
Hi there,

I have a couple of remarks:
- The GitHub issues tab is not meant for "how do I do X with borb?" but rather for bugs and feature requests.
- There are templates (for bugs and feature requests) which you can use
- Your question comes down to "how can I get the bytes of the PDF", which has been asked before:
  - It has been asked as a GitHub issue (see )
  - It has been asked on StackOverflow as a question, tagged with `borb`

**Comment by IAyala** [comment]
Thank you for your help, I apologize for not having noticed this question as a duplicate. I think adding this example would be useful. Thank you and sorry again for my ignorance. Regards

**Comment by orklann** [comment]
@jorisschellekens Your answers are always detailed yet clean and useful in my all my Github issue I have ever seen.
