### ISSUE TITLE
disjoint_set.pop(x) not implemented

### ISSUE THREAD

**Issue by FabRice6** [jorisschellekens/borb#132]
The pop method of the `disjoint_set.py` datastructure is empty (just returns self) :-).

**Comment by jorisschellekens** [comment]
`disjointset` does not need to implement `pop`.

I also believe it would not be able to implement this operation without seriously undermining the performance, as you'd need to track how unions were made, and whether the creation of a union was made possible by a now deleted element.

In the next release, calling this method will raise a `NotImplementedError`

Kind regards,
Joris Schellekens
