### ISSUE TITLE
BUG - table alignment ?

### ISSUE THREAD

**Issue by dt215git** [jorisschellekens/borb#133]
**Describe the bug**
Table alignment doesn't appear to work

**To Reproduce**
Running [chapter_009/src/snippet_004.py](https://github.com/jorisschellekens/borb-examples/blob/master/chapter_009/src/snippet_004.py) should produce a centered table, but it's being positioned on the left. Changing the line below to  **Alignment.LEFT**, **Alignment.CENTERED** or **Alignment.RIGHT** doesn't make any difference to its positioning.

```python
    t: Table = FlexibleColumnWidthTable(
        number_of_rows=9, number_of_columns=9, horizontal_alignment=Alignment.CENTERED
    )
```

**Expected behaviour**
Table is left, right, or centered based on **horizontal_alignment** parameter

**Screenshots**
![image](https://user-images.githubusercontent.com/86194065/189492275-1f2c0282-6904-4fee-b209-3067ff48501b.png)

**Desktop (please complete the following information):**
 - OS: Linux Mint 21 Cinnamon, kernel 5.15.0-47-generic
 - borb version: 2.1.0

**Additional context**
Same happens with a simpler script. The first paragraph is aligned centrally, but the table isn't despite both being set as **horizontal_alignment=Alignment.CENTERED**.
```
from pathlib import Path
from borb.pdf.pdf import PDF
from borb.pdf.document.document import Document
from borb.pdf.page.page import Page
from borb.pdf.canvas.layout.page_layout.multi_column_layout import SingleColumnLayout
from borb.pdf.canvas.layout.table.flexible_column_width_table import FlexibleColumnWidthTable
from borb.pdf.canvas.layout.text.paragraph import Paragraph
from borb.pdf.canvas.layout.table.table import TableCell
from borb.pdf.canvas.layout.layout_element import Alignment
from decimal import Decimal

pdf = Document()
page = Page(width = Decimal(6*72), height = Decimal(9*72))
pdf.add_page(page)
layout = SingleColumnLayout(page)
layout.add(Paragraph("*** TITLE ***", horizontal_alignment = Alignment.CENTERED))

table = FlexibleColumnWidthTable(number_of_rows = 5, number_of_columns = 5, horizontal_alignment = Alignment.CENTERED)
for i in range(25):
    table.add(TableCell(Paragraph('x', text_alignment=Alignment.CENTERED)))
layout.add(table)

layout.add(Paragraph('''
Delectus voluptatem laborum aliquam perferendis. Reiciendis voluptas eius eveniet neque quia dolorum amet earum. Nisi vel necessitatibus est ab est nisi. Nesciunt provident exercitationem ut sed saepe sunt quo commodi.
'''))

with open(Path("output.pdf"), "wb") as pdf_file_handle:
    PDF.dumps(pdf_file_handle, pdf)
```
![image](https://user-images.githubusercontent.com/86194065/189493226-a56ba9aa-01bf-48de-9995-58f6faa385d6.png)

**Comment by jorisschellekens** [comment]
A small mistake crept into the release with v2.1.0.
`FlexibleColumnWidthTable` always returns its width as being that of the encompassing container.

This means centering the `Table` doesn't really do much, since this is normally achieved by shifting all `LayoutElement` objects inside the `Table` by half of the remaining width (which is 0 because of aforementioned bug).

I'm working on a solution.

Kind regards,
Joris Schellekens

**Comment by jorisschellekens** [comment]
Fixed, and added a test t make sure it doesn't happen again.
You may expect this fix in the next release.

Kind regards,
Joris Schellekens
