### ISSUE TITLE
Feature Request: Control image quality when saving/converting

### ISSUE THREAD

**Issue by 13hakta** [jorisschellekens/borb#136]
**Is your feature request related to a problem? Please describe.**
I would like to control quality of inserted images.

**Describe the solution you'd like**
Add optional argument "quality" to saving method or upon image loading.

**Additional context**
When you insert a fine-quality jpeg image while exporting pdf it saves with default quality (75) so in a close view you can notice artifacts.

For example take a look here:
https://github.com/jorisschellekens/borb/blob/master/borb/io/write/image/image_transformer.py#L81

**Comment by mfd** [comment]
<img width="771" alt="image" src="https://user-images.githubusercontent.com/2802926/197953062-d2bb46fc-7b0a-468f-acbf-831fecc06be1.png">

**Comment by jorisschellekens** [comment]
Do you have the raw example image you're using?

Kind regards,
Joris Schellekens

**Comment by jorisschellekens** [comment]
Hi @13hakta 

I asked you for the example input document/image.
You did not provide anything within 7 business days, so I am closing this ticket.
If you would like to re-open the ticket, simply attach an example and re-open.

Kind regards,
Joris Schellekens
