### ISSUE TITLE
Support for single-layer images

### ISSUE THREAD

**Issue by milovanderlinden** [jorisschellekens/borb#139]
**Is your feature request related to a problem? Please describe.**
When I try to ocr a pdf containing single-layer images, processing the file fails. I have narrowed down the problem to the file `ocr_image_render_event_listener.py` line **314** where a color_tuple variable is assumed to be a tuple which is not the case for single-layer images as described in the PIL documentation at https://pillow.readthedocs.io/en/stable/_modules/PIL/Image.html#Image.getpixel

**Describe the solution you'd like**
I would like borb to be able to process single-layer images

**Describe alternatives you've considered**
I haven't considered any alternatives, I just wanted to report this.

**Comment by jorisschellekens** [comment]
Can you attach the PDF you were testing?
Then I can fix this, and add the PDF as a test.

Kind regards,
Joris Schellekens

**Comment by jorisschellekens** [comment]
Hi @milovanderlinden,

I asked you to provide an example input document to allow me to fix this (and then test my fix).
You did not respond within 7 business days, so I am closing this ticket.

Kind regards,
Joris Schellekens
