### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by gschaeffer** [jorisschellekens/borb#144]
**Describe the bug**
Running the Hello World example on the README I'm getting
Traceback (most recent call last):
  File "/Users/garrett/Downloads/_pdf/borb.py", line 3, in <module>
    from borb.pdf import Document
  File "/Users/garrett/Downloads/_pdf/borb.py", line 3, in <module>
    from borb.pdf import Document
ModuleNotFoundError: No module named 'borb.pdf'; 'borb' is not a package

**Reproduce**
I've installed as described in the README 1.0 and copied the example from the README 1.1 Hello World
```
pip install borb


from pathlib import Path

from borb.pdf import Document
from borb.pdf import Page
from borb.pdf import SingleColumnLayout
from borb.pdf import Paragraph
from borb.pdf import PDF

# create an empty Document
pdf = Document()

# add an empty Page
page = Page()
pdf.add_page(page)

# use a PageLayout (SingleColumnLayout in this case)
layout = SingleColumnLayout(page)

# add a Paragraph object
layout.add(Paragraph("Hello World!"))
    
# store the PDF
with open(Path("output.pdf"), "wb") as pdf_file_handle:
    PDF.dumps(pdf_file_handle, pdf)
```

```python
# please enter a concise, complete and self-contained code sample
# that reproduces the bug
```

**Expected behaviour**
I expected the PDF to be created 

**Screenshots**
None

**Desktop (please complete the following information):**
 - OS: Mac - 13.0.1
 - borb version - 2.1.6
- input PDF - example code

**Additional context**
Pretty much just running the example Hello World in the README

**Comment by jorisschellekens** [comment]
Hi @gschaeffer,

I would check the logs/output from `pip`.
To me, it seems like you haven't really installed `borb` (hence the `ModuleNotFoundError`).

You may have conflicting dependencies, or perhaps you are using a virtual environment (and accidentally installed `borb` in the wrong directory)

I know from the usage statistics that `borb` is able to run on all major OS's.

Kind regards,
Joris Schellekens
