### ISSUE TITLE
Add Table of Contents from Bookmark

### ISSUE THREAD

**Issue by ldXiao** [jorisschellekens/borb#147]
I am not sure how the bookmarks are stored in pdf files, but I don't think it will be harder than adding annotation links.
This will be an extremely useful feature.

**Comment by ldXiao** [comment]
I closed it because I saw something issue similar, but I have checked the example repo. Adding Bookmark is different from generating headings from contents. If we start from an existing pdf without TOC, adding bookmark tree is a only way to generate the TOC in this case.

**Comment by jorisschellekens** [comment]
Hi,

I am going to close this issue.
It's very unclear to me what you want.

You mentioned:
- bookmarks
- annotations
- outlines
- table of contents

You also mentioned you closed the issue.

You also didn't follow the template.

Feel free to open another issue if you can clearly define what you want. Perhaps even include screenshots? 

Kind regards,
Joris Schellekens
