### ISSUE TITLE
Letter Spacing

### ISSUE THREAD

**Issue by sourceful-wing** [jorisschellekens/borb#153]
**Is your feature request related to a problem? Please describe.**
Many fonts need letter spacing adjustments especially if you want to add text to an existing PDF that already has a certain style. It's great to have font support, colours and sizing support but letter spacing is an important addition for consistency.

**Describe the solution you'd like**
An ability to specify the letter spacing in % terms (e.g. -2% or 5%)

**Describe alternatives you've considered**
I've not been able to find a way to do it with the library. I thought about trying to generate TTF variables with updated letter spacings but I don't think that's a user friendly solution.

**Additional context**
I really like the library!

**Comment by jorisschellekens** [comment]
This is going to be tricky.
For now, the easiest option would be to give you a parameter `character_spacing` that adds/subtracts a few extra units whenever characters are being rendered.

And even that option would require me to run that parameter through (almost) every `LayoutElement`.

I'll have to think about this.

Kind regards,
Joris Schellekens

**Comment by jorisschellekens** [comment]
Your request has been implemented in the new major version of `borb`, which is currently in development.

The following code:

```python
    def test_chunk_character_spacing_02(self):

        d: Document = Document()

        p: Page = Page()
        d.append_page(p)

        l: PageLayout = SingleColumnLayout(p)
        l.append_layout_element(
            Chunk(
                "Lorem Ipsum",
                border_color=X11Color.RED,
                border_width_top=1,
                border_width_right=1,
                border_width_bottom=1,
                border_width_left=1,
                character_spacing=0.2,
            )
        )

        PDF.write(what=d, where_to="assets/test_chunk_character_spacing_02.pdf")
```

yields the following document:

![image](https://github.com/user-attachments/assets/2ec4575a-d7fa-4c41-b1f9-174c3072a8dc)
