### ISSUE TITLE
How to set OCG layer’s Locked state to True/False?

### ISSUE THREAD

**Issue by ranga-tolapi** [jorisschellekens/borb#159]
How to set OCG layer’s Locked state to True/False? So that, it shall reflect in the layer properties in adobe viewer. Please refer to the following screenshot.

![E7888622-3871-4B19-BC74-DC4026F3F758](https://user-images.githubusercontent.com/17163418/230755240-71945457-6598-4113-9b1d-50c068cccf3d.jpeg)

**Comment by jorisschellekens** [comment]
Hi @ranga-tolapi,

There is no utility function that will allow you to set this property easily.

However, `borb` represent a PDF document as a JSON-like object of nested arrays and dictionaries. So if you know where to look, you can simply change the PDF that way.

There is an example in the examples repository that handles OCG layers (the example uses these layers to insert the result of OCR into a PDF). You can look up that example and see how the code interacts with those layers.

Furthermore, the PDF specification is included in the repository. You can use it to get an idea of which property you would need to set.

Kind regards,
Joris Schellekens
