### ISSUE TITLE
cannot import name 'SingleColumnLayout'

### ISSUE THREAD

**Issue by virtualritz** [jorisschellekens/borb#16]
Just trying out the hello world from the README,  I get this:

```
Traceback (most recent call last):
  File "/Users/moritz/code/python/csv2sheets/src/test.py", line 3, in <module>
    from ptext.pdf.canvas.layout.page_layout import SingleColumnLayout
ImportError: cannot import name 'SingleColumnLayout' from 'ptext.pdf.canvas.layout.page_layout' (/Users/moritz/.local/share/virtualenvs/csv2sheets-vAENhi9u/lib/python3.9/site-packages/ptext/pdf/canvas/layout/page_layout/__init__.py)
```

This is the only part that doesn't import. All the other imports work (if I e.g. switch the order).

I am on macOS, I installed `ptext` (2.0.4) with :

```
❯ pipenv install ptext-joris-schellekens
Installing ptext-joris-schellekens...
Adding ptext-joris-schellekens to Pipfile's [packages]...
✔ Installation Succeeded
Pipfile.lock (c8522f) out of date, updating to (9af5ab)...
Locking [dev-packages] dependencies...
Locking [packages] dependencies...
Building requirements...
Resolving dependencies...
✔ Success!
Updated Pipfile.lock (9af5ab)!
Installing dependencies from Pipfile.lock (9af5ab)...
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 0/0 — 00:00:00
```
```
❯ pipenv shell
Launching subshell in virtual environment...
 . /Users/moritz/.local/share/virtualenvs/csv2sheets-vAENhi9u/bin/activate
    ~/code/python/csv2sheets  loading 
❯  . /Users/moritz/.local/share/virtualenvs/csv2sheets-vAENhi9u/bin/activate
```

**Comment by jorisschellekens** [comment]
Hi Moritz,

I think the README is just a bit out of date.
If you are using an IDE, it might automatically find the right import (assuming you remove the wrong one).

It should be in `ptext

**Comment by jorisschellekens** [comment]
Hi Moritz,

I built a new release:
- Updated the README.md
- Added some more tests (including the hello world from the README.md)
- etc

Check the releasenotes to find out exactly what changed.
I verified the code in the hello world, it should work now.

I am going to close this issue.
I would really appreciate it if you could star my repo.
Right now, word of mouth, and imaginary internet points is all I am getting from this library :-)

Kind regards,
Joris Schellekens
