### ISSUE TITLE
invisible text layer

### ISSUE THREAD

**Issue by lbr991** [jorisschellekens/borb#168]
I'm trying to take a non-searchable pdf and convert it to searchable pdf by superimposing an invisible text layer.
I need the invisible text bboxes to align exactly with the original bboxes (extracted by Textract).
I also don't want to specify a font and font_size because then the bboxes wouldn't align perfectly.

Is this possible with borb?

**Comment by jorisschellekens** [comment]
Hi there,

I will refer you to the examples repository, where you can find an exact example of this usecase. 

https://github.com/jorisschellekens/borb-examples#72-performing-ocr-on-a-pdf

If you have any further questions, please check the documentation, examples and GitHub first.

Kind regards,
Joris Schellekens

**Comment by lbr991** [comment]
Thanks for the quick reply! 

Is there a way to create invisible text where the bboxes match exactly the original bbox (scanned pdf)? From the example I see it is selecting a font size.
