### ISSUE TITLE
Need to get fonts and text and bounding boxes for each word in the document

### ISSUE THREAD

**Issue by HenryJCobb** [jorisschellekens/borb#170]
As you can see from the code below I've got word index, word text, and bounding box.
Now I'd like to have font family, font size, and font style (bold, italic, underline...) as well, but borb.toolkit.text.regular_expression_text_extraction seems to throw most font details away and only returns font_color and font_size

How do I get the font size, style, and family for each word (or glyph I suppose)?

```python
import sys
import os
import typing
from borb.pdf import Document
from borb.pdf.pdf import PDF
from borb.pdf.canvas.geometry.rectangle import Rectangle
from borb.toolkit.text.regular_expression_text_extraction import RegularExpressionTextExtraction, PDFMatch

maxfont: int = -1
fontDict = {}
wordList = []

def main():
    if 2 > len(sys.argv):
        print("Please specify the PDF file to operate on")
        exit()

    inputFile = os.path.abspath(sys.argv[1])
    assert os.path.exists(inputFile)
    workingDir = os.path.dirname(inputFile)
    inputName = os.path.basename(inputFile)

    # Deleting a lot of database insert stuff here    
    d: typing.Optional[Document] = None
        
    # Set up EventListener
    l: RegularExpressionTextExtraction = RegularExpressionTextExtraction("[^ ]+")
    with open(inputFile, "rb") as pdf_in_handle:
        d = PDF.loads(pdf_in_handle, [l])

    assert d is not None

    for i, m in enumerate(l.get_matches()[0]):
        print("%d %s" % (i, m.group(0).encode("utf-8")))
        for r in m.get_bounding_boxes():
            print(
                "\t%f %f %f %f" % (r.get_x(), r.get_y(), r.get_width(), r.get_height())
            )

if __name__ == "__main__":
    main()
```

**Comment by jorisschellekens** [comment]
I think the easiest (perhaps even more performant) way of doing this would be:
- build your own version of `RegularExpressionTextExtraction`
- build your own `EventListener` implementation

At the very lowest level, you would have access to the complete state of the renderer when it is rendering text. Including font information and geometry information.

Keep in mind there will be some things that may not generalize well.
For instance determining whether a font is bold or not.

- You can extract the name of the font (but there are no rules for what the name ought to be. Maybe it contains "bold" maybe it doesn't)
- You can look at the `FontDescriptor`, it has a property `FontWeight`. But that property is optional.

![image](https://github.com/jorisschellekens/borb/assets/18642798/8273890a-da87-4796-bbcc-8e76f17bf7bb)

Kind regards,
Joris Schellekens
