### ISSUE TITLE
Multiple Column Layout

### ISSUE THREAD

**Issue by aleksandar-devedzic** [jorisschellekens/borb#175]
Is there a function to create multiple column layout?

Image if I want to create newspapper page. I would like to add text (headline, lead, body) + image.

Is there a way to add text that will be represented in multiple columns, and then add an image?

**Comment by jorisschellekens** [comment]
Hi @aleksandar-devedzic,

There are a couple of things you could try:
1. Write your own implementation of `PageLayout`
2. Use a `Table` (setting `col_span` where needed)
3. Use absolute positioning for everything

Kind regards,
Joris Schellekens
