### ISSUE TITLE
BUG PageDictionaryTransformer prints "reading page"

### ISSUE THREAD

**Issue by BjornFJohansson** [jorisschellekens/borb#176]
**Describe the bug**
borb PageDictionaryTransformer prints "reading page" to the consol when reading pdfs.

**To Reproduce**
Steps to reproduce the behaviour:

```python
doc = PDF.loads(in_file_handle)
```

**Expected behaviour**
Not print anything. If this is a feature, please ignore.

**Comment by jorisschellekens** [comment]
This is definitely *not* a feature.

Probably some output I added for debugging a problem, that I forgot to remove.

I'll make sure this gets cleaned up in the next release.

**Comment by jorisschellekens** [comment]
fixed in `v2.1.18`
