### ISSUE TITLE
CropBox

### ISSUE THREAD

**Issue by 6801318d8d** [jorisschellekens/borb#178]
I would like to remove the Crop Box from a PDF file, or change is size.

Can borb do that? Because I can't find anything in the examples.

**Comment by jorisschellekens** [comment]
`borb` represents a PDF as a JSON-like datastructure.
You can easily do this kind of low-level operation by modifying the "PDF as JSON".
In your particular case, look at `doc['XRef']['Trailer']['Root']['Pages']['Kids'][0]['CropBox']`

Also, in future please use StackOverflow to ask for help.
Issues are meant for bugs and feature-requests.

Kind regards,
Joris Schellekens
