### ISSUE TITLE
Justified alignment not working?

### ISSUE THREAD

**Issue by eternalstarfire** [jorisschellekens/borb#18]
I just had a look at an [example test output](https://github.com/jorisschellekens/borb/blob/master/tests/output/test_write_line_of_text_justified_full/output.pdf), the alignment of the paragraph didn't appear to be justified:

![image](https://user-images.githubusercontent.com/35546598/129495804-d2821fb1-409f-44ae-b755-248757a5c5df.png)

Thought I'd mention in in case you weren't aware.

**Comment by jorisschellekens** [comment]
Hi there,

Thank you for taking the time to look through the tests.
This test is a bit misleading. It sets the parameter `text_alignment` but does not expect the result to have changed.
This behaviour is expected and documented:
https://github.com/jorisschellekens/borb/blob/5b2ab0f582479d2e8d002d0450eedcacc64d208a/borb/pdf/canvas/layout/text/line_of_text.py#L42

Short explanation of how layout works (in borb) for a `Paragraph`:

1. Split the `str` into tokens (on space, tab and other chars)
2. Given the width of the bounding box that was passed to the `_do_layout` method, calculate the lines of text that will make up the `Paragraph` (the return type here is `typing.List[str]`)
3. If the `text_alignment` is set to `Alignment.JUSTIFIED` (and not rendering the last line of text), calculate the remaining space
4. Instantiate `ChunkOfText` objects (one for each token), and calculate their position (using the width they would normally have + their share of `remaining_space`)

So, when performing layout with `text_alignment` set to `Alignment.JUSTIFIED`) on a `Paragraph`, you are not even using `LineOfText` objects :-)

I hope that clears up the issue, and alleviates your concern.

Kind regards,
Joris Schellekens
