### ISSUE TITLE
BUG: Python version 3.6 does not support parenthesized context expressions

### ISSUE THREAD

**Issue by yathon** [jorisschellekens/borb#184]
**Describe the bug**

> Traceback (most recent call last):
>   File "/.../src/main.py", line 5, in <module>
>     from borb.pdf import PDF
>   File "/.../venv/lib/python3.6/site-packages/borb/pdf/__init__.py", line 107, in <module>
>     from .canvas.layout.geography.map_of_europe import MapOfEurope
>   File "/.../venv/lib/python3.6/site-packages/borb/pdf/canvas/layout/geography/map_of_europe.py", line 16, in <module>
>     from borb.pdf.canvas.layout.geography.map import Map
>   File "/.../venv/lib/python3.6/site-packages/borb/pdf/canvas/layout/geography/map.py", line 67
>     with (open(geojson_file, "r") as json_file_handle):
>                                    ^
> SyntaxError: invalid syntax

**Env**

OS: MacOS Sonoma 14.1.1
Python: Python 3.6.8
DevTool: Pycharm 2022.3

**Sources code**

```Python
#!chapter_005/src/snippet_002.py
# import typing
# from borb.pdf import Document
from borb.pdf import PDF

def main():
    # read the Document
    # doc: typing.Optional[Document] = None
    with open("../doc/test.pdf", "rb") as in_file_handle:
        doc = PDF.loads(in_file_handle)

    # check whether we have read a Document
    assert doc is not None

    # print the \Author key from the \Info dictionary
    print("Author: %s" % doc.get_document_info().get_author())

if __name__ == "__main__":
    main()
```

**Remark** 

Is the example code outdated or is Python 3.6 no longer supported?

**Comment by yathon** [comment]
Python3.7.9: Python version 3.7 does not support parenthesized context expressions

The same error as Python3.6.8.

>         # /.../venv/lib/python3.7/site-packages/borb/pdf/canvas/layout/geography/map.py
>         # read map
>         with (open(geojson_file, "r") as json_file_handle):
>                                                            ^

**Comment by jorisschellekens** [comment]
In the dev repo, I added a workflow that will automatically run a single test, in multiple python versions.
I saw that this failed (same error as the one you have) and fixed the error.
You can expect support for version 3.7 and upwards.

![image](https://github.com/jorisschellekens/borb/assets/18642798/adfaa8d0-31bd-4fe8-9682-e91ef0742671)
