### ISSUE TITLE
Set Password For PDF generated

### ISSUE THREAD

**Issue by mfikrin** [jorisschellekens/borb#190]
I want to create a pdf and provide a password to the pdf (user password and owner password). Currently, I have succeeded in using a combination with other libraries but I think it takes a very long time if the PDF is large because it has to be dumped first and the other library should read the pdf and encrypted using these other libraries. Currently, is Borb able to set a password for the generated PDF? Thank You

**Comment by jorisschellekens** [comment]
I added the capability to read a password-protected PDF, however **writing a password-protected PDF is currently unsupported.**

**Comment by mfikrin** [comment]
okay, thank you for the answer and confirmation
