### ISSUE TITLE
BUG A3 Template for Landscape isn't different from Portrait 

### ISSUE THREAD

**Issue by SpellingA** [jorisschellekens/borb#191]
**Describe the bug**
In the PageSize Enumeration there are a number of sizes for various pages, each with a landscape and a portrait layout. The A3 Landscape should be 1190,842 however it is 842,1190 Just like the Portrait Layout

**To Reproduce**
Check the code, [here](https://github.com/jorisschellekens/borb/blob/master/borb/pdf/page/page_size.py)

**Expected behavior**
A3_LANDSCAPE = (Decimal(1190), Decimal(842))

**Screenshots**
![image](https://github.com/jorisschellekens/borb/assets/26139251/0ae7443d-cd58-4a05-9c14-5542a9f0ac5f)

**Desktop (please complete the following information):**
 - OS: Windows
 - borb version: 2.1.21

**Additional context**

**Comment by jorisschellekens** [comment]
Fixed in dev repo.
Shall be fixed in next release.

Thank you for spotting it!

Kind regards,
Joris Schellekens
