### ISSUE TITLE
Form created are unable to be viewed in pdf xchange editor

### ISSUE THREAD

**Issue by sanksara** [jorisschellekens/borb#195]
Hi, I tried creating a sample pdf with form element using the sample code.
the element created was some text fields.
when I opened the pdf in pdf xchange editor , the form fields were not visible, only a rectangular box was visible which are not editable.
when I opened the file in Acrobat, the form fields are visible and when I entered some text there and saved, the form fields were visible back when I opened in pdf xchange editor.

may I know what is issue here? I dodnot face the same when form was created using other modules like pdfrw etc..

**Comment by jorisschellekens** [comment]
Please follow the templates when creating an issue.

**Comment by jorisschellekens** [comment]
Closing this issue.
You did not give me any code that enables me to reproduce the issue.
You are welcome to re-submit the issue, assuming you do follow the template next time around.

Kind regards,
Joris Schellekens
