### ISSUE TITLE
Unable to Push Commits to Remote Repository

### ISSUE THREAD

**Issue by rhalloy01** [jorisschellekens/borb#198]
Hey, I’m Jenny and I work at [R.H. Alloys](https://rhalloys.com/stainless-steel-sheet-manufacturer-india/). I am unable to send my local commits to the GitHub remote repository due to a problem. I've double-checked my login information, made sure I have the appropriate authorization, and examined my internet connection. I continue to receive an authentication error in spite of these checks. Any thoughts or answers would be highly valued.

**Comment by jorisschellekens** [comment]
Hi Jenny,

`borb` is open source, but that does not automatically mean anyone is allowed to commit code to the repository.

If you want to contribute code, you should:
- read the information for contributors
- sign (and send me) the contributor license agreement
- create a pull request

Kind regards,
Joris Schellekens

**Comment by jorisschellekens** [comment]
Also,

Keep in mind your code needs to be open source if you want to use `borb` free of charge. If your code is not open source, you need to purchase a license from us.

Kind regards,
Joris Schellekens
