### ISSUE TITLE
BUG, Unable to read PDF file

### ISSUE THREAD

**Issue by Tim-Bolhoeve** [jorisschellekens/borb#199]
**Describe the bug**
Unable to read PDF file using borb.pdf's PDF class when trying to load it. Console error: `signal only works in main thread of the main interpreter` (using Django with a venv, if that matters)

**To Reproduce**
Steps to reproduce the behaviour:

```python
from borb.pdf import PDF
from borb.pdf import Document
import typing

@login_required()
def myFunction(request):
    if request.user.is_authenticated:
        try:
            file_dict = {}
            file_dir = f"{settings.MEDIA_ROOT}"
            file_list = list(glob(f'{file_dir}/*.pdf'))
            if file_list != []:
                for idx, file_path in enumerate(file_list):
                    filename_only = os.path.basename(file_path)
                    file_date_time = datetime.fromtimestamp(os.path.getmtime(file_path)).strftime('%Y-%m-%d %H:%M:%S')
                    
                    # read PDF using borb, to check if pdf file has any signatures
                    doc: typing.Optional[Document] = None
                    with open(f"{file_dir}/{filename_only}", "rb") as pdf_file_handle:
                        doc = PDF.loads(pdf_file_handle)

                    file_dict[idx] = {
                        'datetime': file_date_time,
                        'path': f"<a href='{settings.MEDIA_URL}/{filename_only}' download>{filename_only}</a>",
                        'filename': filename_only
                    }
        except Exception as e:
            print(e) # error is shown here
            return redirect('index')

        context = {
            "file_dict": file_dict
        }
        return render(request, "myHtml.html", context)
    else:
        return redirect('login')
```

**Expected behaviour**
The expected behavior is that the PDF file would be read after which i can do something like `doc.get_document_info().has_signatures()`

**Screenshots**
![Screenshot 2024-03-08 115906](https://github.com/jorisschellekens/borb/assets/74612255/189f1296-1c4d-4968-ad04-56f1de153a64)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - borb version: borb==2.1.21

**Additional context**
Source: code from which i tried to implement: https://stackoverflow.com/a/74521043/19868773

**Comment by jorisschellekens** [comment]
`borb` introduced anonymous usage statistics a while ago (I mentioned it in the release notes, and provided ways of disabling them).

In this particular case, `borb` is attempting to register itself for the `when the program ends` signal.
But sadly signal doesn't seem to allow that unless you are actually the main thread. Which, given your context is not the case.

The easiest solution would be to disable the anonymous usage statistics.

You should be able to call `AsyncUsageStatistics.disable()` (it is a static method, so calling it once before executing `borb` code should be fine).

I'm also going to change the code to ensure it doesn't attempt to register for that event unless it is actually on the main thread.

**Comment by Tim-Bolhoeve** [comment]
That seems to have worked.

For anyone ever visiting this issue, the fix was:
```python
from borb.license import async_usage_statistics
async_usage_statistics.AsyncUsageStatistics.disable()
```
Which I made global

**Comment by chrisgelinek-rl** [comment]
For reference, the code now seems to be
```
from borb.pdf.license.usage_statistics import UsageStatistics
UsageStatistics.opt_out()
```

I used it to disable the following (ignored) exception raised at exiting the interpreter:
```
Exception ignored in atexit callback: <function UsageStatistics.__empty_queue at 0x7f3d13a87c40>
Traceback (most recent call last):
  File "/net/groper/u1/home/cgelinek/Documents/borb/.venv/lib/python3.11/site-packages/borb/pdf/license/usage_statistics.py", line 71, in __empty_queue
    import requests  # type: ignore[import-untyped]
    ^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'requests'
```
...which almost sounds like a separate issue, either `requests` should be added to the dependencies or `UsageStatistics` should use another way of "phoning home"?
