### ISSUE TITLE
Can't import 'image'

### ISSUE THREAD

**Issue by paulr4** [jorisschellekens/borb#20]
Hi,

The line:
`from borb.pdf.canvas.layout.image import Image`

gives an error:
`ImportError: cannot import name 'Image' from 'borb.pdf.canvas.layout.image' (/home/user/.local/lib/python3.7/site-packages/borb/pdf/canvas/layout/image/__init__.py)`

Am I doing something wrong?

**Comment by jorisschellekens** [comment]
Hi there,

You can always check out one of the test that works with images, and verify your imports.

For instance:
https://github.com/jorisschellekens/borb/blob/master/tests/pdf/canvas/layout/image/test_write_image_by_url.py

That test attempts to write an image to a pdf when a URL is specified.

**Comment by paulr4** [comment]
Thanks for the fast response. The test above simply freezes with no outputs. If I ctrl-c after 5 minutes or so I get:
`^CTraceback (most recent call last):
  File "test_write_image_by_url.py", line 81, in <module>
    unittest.main()
  File "/usr/lib/python3.7/unittest/main.py", line 100, in __init__
    self.parseArgs(argv)
  File "/usr/lib/python3.7/unittest/main.py", line 147, in parseArgs
    self.createTests()
  File "/usr/lib/python3.7/unittest/main.py", line 156, in createTests
    self.test = self.testLoader.loadTestsFromModule(self.module)
  File "/usr/lib/python3.7/unittest/loader.py", line 124, in loadTestsFromModule
    tests.append(self.loadTestsFromTestCase(obj))
  File "/usr/lib/python3.7/unittest/loader.py", line 93, in loadTestsFromTestCase
    loaded_suite = self.suiteClass(map(testCaseClass, testCaseNames))
  File "/usr/lib/python3.7/unittest/suite.py", line 24, in __init__
    self.addTests(tests)
  File "/usr/lib/python3.7/unittest/suite.py", line 57, in addTests
    for test in tests:
  File "test_write_image_by_url.py", line 27, in __init__
    while "output" not in [x.stem for x in p.iterdir() if x.is_dir()]:
  File "test_write_image_by_url.py", line 27, in <listcomp>
    while "output" not in [x.stem for x in p.iterdir() if x.is_dir()]:
  File "/usr/lib/python3.7/pathlib.py", line 1083, in iterdir
    for name in self._accessor.listdir(self):
KeyboardInterrupt`

I do notice that the test uses:
`from borb.pdf.canvas.layout.image.image import Image`
where the [example I am following](https://github.com/jorisschellekens/borb-examples) used:
`from borb.pdf.canvas.layout.image import Image`
...perhaps this is a mistake?

Fixing it in my original program surfaces another error:
`from borb.pdf.canvas.layout.paragraph import Paragraph, Alignment`
which I can fix by changing to to:
`from borb.pdf.canvas.layout.text.paragraph import Paragraph, Alignment`

This leads to another error caused by:
`PDF.dumps(pdf_file_handle, document)`
instead of
`PDF.dumps(pdf_file_handle, Document)`

After all this, the script runs, but produces a zero-length pdf. I'm still trying to get to the bottom of this but thought you'd appreciate the findings above in the meantime.

**Comment by paulr4** [comment]
Please note the tutorial is also [here](https://stackabuse.com/creating-pdf-invoices-in-python-with-borb/) if you're making corrections!

**Comment by paulr4** [comment]
I discovered the output line should read:
`PDF.dumps(pdf_file_handle, pdf)`
rather than:
`PDF.dumps(pdf_file_handle, document)`

**Comment by jorisschellekens** [comment]
Which example is that?
Your link just takes me to the top of the document

**Comment by paulr4** [comment]
The invoice example. I'm still struggling to get it to output a complete invoice. I wonder if pasting the finished example into the article might avoid any chance of mistakes creeping in?

**Comment by paulr4** [comment]
On further reading, I see you already have that in the [github examples page](https://github.com/jorisschellekens/borb-examples), and it works fine.

The errors I've highlighted are all in the snippets of code within the tutorial; building these together is what causes the problems. Unfortunately the [Stackabuse](https://stackabuse.com/creating-pdf-invoices-in-python-with-borb/) article doesn't have the completed code at the end, and that's what I was initially following.

**Comment by jorisschellekens** [comment]
The StackAbuse article was written before a large refactor (during which I put all similar layout elements in the same package).

That's why this is happening.

I'll try running the snippets from that tutorial again, just to check what needs to be tweaked.

**Comment by jorisschellekens** [comment]
I'm pretty sure the test is ok though. I try to release every weekend, before each release I run the tests. So that should be fine.

**Comment by paulr4** [comment]
The article is the first google hit for 'python invoice generator', and may be many peoples' first contact with Borb, so hopefully worth correcting!

As for the test, I'm running it in WSL, perhaps that's introducing a problem? Anyway it's not impacting anything for me.

Thanks for your interest and your hard work on Borb.

**Comment by jorisschellekens** [comment]
I changed the imports in the tutorial :-)
https://stackabuse.com/creating-pdf-invoices-in-python-with-borb/

**Comment by jorisschellekens** [comment]
It's definitely worth correcting, but I don't know to which degree I am allowed to modify the article after it has been approved by them. Fixing a few imports seems an obvious "yes". But changing the structure (for instance by adding the full code-sample at the end) seems riskier.

**Comment by jorisschellekens** [comment]
I think it's fixed now. Just to make sure I'm also re-running the entire test-suite.
Can you verify whether the tutorial looks good now?

**Comment by paulr4** [comment]
Yes I think the Stack Abuse article is fixed now. Same errors in the github examples though.

**Comment by jorisschellekens** [comment]
Ok, I'll fix those after lunch.

**Comment by jorisschellekens** [comment]
Fixed.
Please verify :-)

**Comment by paulr4** [comment]
Yes it all looks good to me. Thanks for responding so fast and for maintaining the project, I look forward to using it.

**Comment by jorisschellekens** [comment]
You're welcome.
Thanks for taking the time to log an issue.
