### ISSUE TITLE
Bug with MultiColumnLayout

### ISSUE THREAD

**Issue by beucismis** [jorisschellekens/borb#203]
**Describe the bug**

```
Traceback (most recent call last):
  File "/home/user/python/test.py", line 56, in <module>
    main()
  File "/home/user/python/test.py", line 23, in main
    l: PageLayout = MultiColumnLayout(p)
                    ^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.11/site-packages/borb/pdf/canvas/layout/page_layout/multi_column_layout.py", line 47, in __init__
    assert len(column_widths) >= 1
           ^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
```

**To Reproduce**

Example: https://github.com/jorisschellekens/borb-examples?tab=readme-ov-file#512-removing-pages-from--pdf-documents

**Desktop (please complete the following information):**

 - OS: Devuan GNU/Linux
 - borb version 2.1.22

**Comment by jorisschellekens** [comment]
That should be 'TwoColumnLayout' (which can be imported as 'from borb.pdf.canvas.layout.page_layout.multi_column_layout import TwoColumnLayout')

I am going to add 'TwoColumnLayout' to the easy imports in the next release, and fix this mistake in the examples.

**Comment by beucismis** [comment]
Thanks.
