### ISSUE TITLE
Question : How to draw separation line

### ISSUE THREAD

**Issue by lguerard** [jorisschellekens/borb#207]
Sorry, more of a stupid question than a real feature request.

What's the best way to draw a separation line between part of my document ? Something that separates, like on this [document](https://www.sampletemplatess.com/free-marriage-separation-agreement-template/).

I had a look and wanted to draw a very thin rectangle, but if I understood correctly, this requires the coordinates of the rectangle, and I'm not sure how to get the current position on the page.
I also tried using a `Table` of a single line, but couldn't figure out how to reduce the thickness of the line. Setting up the padding with `Decimal(0.01)` didn't change much...

Thanks for your help! !

**Comment by jorisschellekens** [comment]
Hi Laurent,

I visited your link (to the example document) on my phone. It took me to a spam-page that tried to play a video.

Do not post this kind of link again. I do not want people visiting the previous issues, and getting their computer infested with malware.

Concerning your issue:
- Use `HorizontalRule`
- In future, please ask your question on Stackoverflow. `borb` has its own tag there. The issues tab on Github is meant for bugs and feature requests.

Kind regards,
Joris Schellekens

**Comment by lguerard** [comment]
Sorry about the link, I just did a quick search and linked the first website/image that I could find with a separation line. This was really not intentional.

I'll post on Stackoverflow then, thanks a lot !
