### ISSUE TITLE
AttributeError: 'SimpleImageExtraction' object has no attribute 'get_images_per_page'

### ISSUE THREAD

**Issue by stordopoulos** [jorisschellekens/borb#21]
Greetings,

I'm trying to test Borb, but I am getting an error message that ```'SimpleImageExtraction' object has no attribute 'get_images_per_page'```.

The code is pretty straight forward:

```
# Import borb
import borb

from borb.toolkit.image.simple_image_extraction import SimpleImageExtraction
from borb.pdf.pdf import PDF

from pathlib import Path

# File-wide Variables
source_file_path = Path('python-basics-sample-chapters.pdf')

# Read 'source_file_path' and its info (see 'doc_info')
with open(source_file_path, "rb") as pdf_file_handle:
    l = SimpleImageExtraction()
    doc = PDF.loads(pdf_file_handle, [l])
    doc_info = doc.get_document_info()
    number_of_pages = doc_info.get_number_of_pages()

# Destination folder path
img_path = f'{source_file_path.parent}/{source_file_path.stem}'

# Create a path for 'img_path' if it doesn't already exist
Path(img_path).mkdir(parents=True, exist_ok=True)


print(f'number of pages: {int(number_of_pages)}')

# Serial
serial_results = {}
for page_number in range(int(number_of_pages)):
    serial_results[page_number] = l.get_images_per_page(page_number)
print(serial_results)

```

I usually prototype in Colab, and I usually work with the latest release. This issue appeared after version ```2.0.7```.

- [Link to Colab with Borb 2.0.6](https://colab.research.google.com/drive/1gvmKFN5Vf81rORCDU9xhNMdEDuqlkV3M?usp=sharing): Borb works, but it misses a couple of images in pages
- [Link to Colab with Borb 2.0.6](https://colab.research.google.com/drive/1gvmKFN5Vf81rORCDU9xhNMdEDuqlkV3M?usp=sharing): Borb throws the error ```AttributeError: 'SimpleImageExtraction' object has no attribute 'get_images_per_page'```, and now pip also shows compatibility conflicts between Colab and Borb.

**Comment by jorisschellekens** [comment]
Hi,

The API changed between those versions. If you check the release notes you'll find that I changed the method names for all classes that extract something from a page.

- ‘get_text_for_page‘
- ‘get_images_for_page‘
- ‘get_keywords_for_page‘
- etc

Whereas previously I mixed "for" and "per".

I hope that brings some clarification.

Kind regards,
Joris Schellekens

**Comment by jorisschellekens** [comment]
I think the "missing images" are just not really images.
By that I mean: those images are not embedded images, they are PDF instructions that actually render content directly on the page.

Image something like creating a bar-chart in excel by setting the color and borders of cells. You can do that, and it would look like a chart. But it wouldn't really play nice with the actual charts on the page.

I hope that makes sense.

Kind regards,
Joris Schellekens

**Comment by stordopoulos** [comment]
> I think the "missing images" are just not really images.

That's very interesting. If that's the case, then I guess Borb would be used more like a text extraction tool in my case, and a tool like [Layout Parser](https://github.com/Layout-Parser/layout-parser) to identify the images/tables contextually instead of extracting the image itself.

Thanks for the feedback, Joris.
