### ISSUE TITLE
can you extract/parse  tables from pdf?

### ISSUE THREAD

**Issue by Sandy4321** [jorisschellekens/borb#22]
can you extract/parse  tables from pdf?

lets say pds file with many tables and text /images between them?

**Comment by Sandy4321** [comment]
no
but if you have many pages pdf document with many tables
can it separate table from table 
especially 
when there is text between talbes
meaning real pdf report

**Comment by jorisschellekens** [comment]
What have you tried so far?

**Comment by Sandy4321** [comment]
I wait you  do not confirm it works for real documents
than will try

**Comment by jorisschellekens** [comment]
The examples and tests (where you can see this behaviour demonstrated are open source.

So of course they are real. You can run the code and verify you get the exact same output that I do.

However table detection is a complex problem. I offer no guarantee that my code will work for every possible table out there.

That means the best way for you to go forward is to simply **try it**.

I have a repository that uses Google Colab and borb. You don't even need to install my library on your computer.

It would take you no more than 15 minutes to simply copy/paste the code and see whether it works for your document.
