### ISSUE TITLE
Support for text/image links?

### ISSUE THREAD

**Issue by Mattyfaz** [jorisschellekens/borb#23]
Is there any way to add text / image links into a PDF?

Ideally I'd like to be able to do something like the following:

`table.add(Paragraph("Click this to go to Github", link="https://github.com"))`
OR
`table.add(Image("http://image.com", link="https://github.com"))`

Please let me know if there is some method of performing this functionality that I am missing.

**Comment by jorisschellekens** [comment]
Just wanted to let you know it's in the current release.
Check out [this test](https://github.com/jorisschellekens/borb/blob/master/tests/pdf/page/annotations/test_add_remote_go_to_annotation.py).

You can find its output PDF [here](https://github.com/jorisschellekens/borb/blob/master/tests/output/test_add_remote_go_to_annotation/output_001.pdf).

Kind regards,
Joris Schellekens
