### ISSUE TITLE
Add installation instructions to documentation

### ISSUE THREAD

**Issue by janik6n** [jorisschellekens/borb#27]
To improve the documentation, consider adding installation instructions. Found this package in PyPI, but it does not seem to be stated anywhere on the repo front page, or in the Hello World -example.

**Comment by jorisschellekens** [comment]
Hi there,

Thank you for the feedback.
It has been fixed in the development repository of `borb` and will be pushed with the upcoming release.

Kind regards,
Joris Schellekens
