### ISSUE TITLE
Simplify import paths

### ISSUE THREAD

**Issue by kencx** [jorisschellekens/borb#34]
This library is great and I'm really excited to use it. However, my one complaint is the deeply nested import paths. similar to #25:
```
from borb.pdf.canvas.layout.page_layout.multi_column_layout import SingleColumnLayout
from borb.pdf.canvas.layout.text.paragraph import Paragraph
from borb.pdf.document import Document
from borb.pdf.page.page import Page
from borb.pdf.pdf import PDF
```
My opinion is that its too verbose and any future restructuring of the modules might break the API for existing users. It can be simplified to something like:
```
from borb.pdf.canvas import SingleColumnLayout
from borb.pdf.canvas import Paragraph
from borb.pdf import Document, Page, PDF
```

Relative imports can be added to a module's `__init__.py` for shorter import paths. However, instead of just placing all imports into `borb`'s main `__init__.py`, larger sub-modules like `canvas` can remain separated to maintain a clear structure.

### A proposed example
Using `borb.pdf` as an example, within `borb/pdf/__init__.py`, it can contain:
```
from .pdf import PDF
from .document import Document
from .page.page import Page
from .page.page_info import PageInfo
from .page.page_size import PageSize
from .trailer.document_info import DocumentInfo
from .xref.xref import XREF
from .xref.stream_xref import StreamXREF
from .xref.plaintext_xref import PlainTextXREF
```
Because `canvas` contains so many of its own modules, it can treated as a key sub-module and relative imports from `color,event,font,geometry,layout,line_art,operator` can be added into `canvas/__init__.py`. I tested this out on some of the unit tests and they ran successfully.

Current users can continue to use the current imports if they want but new users can choose to use the simplified imports.

This is just a proposed example that I feel would help to significantly simplify imports, and am happy to hear alternative solutions as well. Thank you for maintaining this btw :)

**Comment by jorisschellekens** [comment]
Hi Kenneth,

Thanks for your feedback.

I know there is a similar issue, which I closed (the author of that issue said he'd make a concrete proposal, and didn't).

The imports are not something that bother me that much. I use IntelliJ, which automatically fills in the imports.

I do understand that the imports are starting to get unwieldy, and I love that you've shown me a concrete way of fixing it.

I'll have to take a closer look at what I'd like the package structure to be. So this ticket may not be resolved quite that easily.

Kind regards,
Joris Schellekens

**Comment by kennethcheo** [comment]
Thanks for the prompt reply! I would be happy to contribute a PR too once the package structure has been decided. And not to worry about resolving this soon, I understand that there are more pressing features.

**Comment by jorisschellekens** [comment]
I've added the following to `borb/pdf/__init__.py`

```python
# PageLayout
from .canvas.layout.page_layout.page_layout import PageLayout
from .canvas.layout.page_layout.multi_column_layout import SingleColumnLayout
from .canvas.layout.page_layout.multi_column_layout import MultiColumnLayout

# Paragraph
from .canvas.layout.text.paragraph import Paragraph
from .canvas.layout.text.heading import Heading

# Image
from .canvas.layout.image.image import Image
from .canvas.layout.image.chart import Chart
from .canvas.layout.image.barcode import Barcode
from .canvas.layout.image.barcode import BarcodeType

# Table
from .canvas.layout.table.table import Table, TableCell
from .canvas.layout.table.fixed_column_width_table import FixedColumnWidthTable
from .canvas.layout.table.flexible_column_width_table import FlexibleColumnWidthTable

# List
from .canvas.layout.list.list import List
from .canvas.layout.list.ordered_list import OrderedList
from .canvas.layout.list.unordered_list import UnorderedList
from .canvas.layout.list.roman_list import RomanNumeralOrderedList

# Color
from .canvas.color.color import Color, RGBColor, CMYKColor, GrayColor, HSVColor, HexColor, HSVColor, X11Color
from .canvas.color.pantone import Pantone
```

As a first iteration, I think it's more than enough to ensure a basic `Document` can be built entirely using these simplified imports.

I've added a new test as well:

```python
import unittest
from pathlib import Path

# simplified imports
from borb.pdf import Document, HexColor
from borb.pdf import Page
from borb.pdf import SingleColumnLayout
from borb.pdf import Paragraph
from borb.pdf import PDF


unittest.TestLoader.sortTestMethodsUsing = None


class TestWriteHelloWorldWithEasierImports(unittest.TestCase):
    def __init__(self, methodName="runTest"):
        super().__init__(methodName)
        # find output dir
        p: Path = Path(__file__).parent
        while "output" not in [x.stem for x in p.iterdir() if x.is_dir()]:
            p = p.parent
        p = p / "output"
        self.output_dir = Path(p, Path(__file__).stem.replace(".py", ""))
        if not self.output_dir.exists():
            self.output_dir.mkdir()

    def test_write_hello_world_with_easier_imports(self):

        # create an empty Document
        pdf = Document()

        # add an empty Page
        page = Page()
        pdf.append_page(page)

        # use a PageLayout (SingleColumnLayout in this case)
        layout = SingleColumnLayout(page)

        # add a Paragraph object
        layout.add(Paragraph("Hello World!", font_color=HexColor("56cbf9")))

        # determine output location
        out_file = self.output_dir / "output.pdf"

        # attempt to store PDF
        with open(out_file, "wb") as out_file_handle:
            PDF.dumps(out_file_handle, pdf)

```
