### ISSUE TITLE
re.Match  to re.match

### ISSUE THREAD

**Issue by pligro** [jorisschellekens/borb#36]
https://github.com/jorisschellekens/borb/blob/9580de963486760263aa4e5d10e5afae60c2587a/borb/toolkit/text/regular_expression_text_extraction.py#L33

**Comment by pligro** [comment]
ubuntu server 18,
Python 3.6.9 (default, Jan 26 2021, 15:33:00)
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import re
>>> re.Match
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 're' has no attribute 'Match'
>>>
i change  re.Match  to  re.match

**Comment by jorisschellekens** [comment]
The module is called `re.match`, but the object is `re.Match`.

As per the documentation:

https://docs.python.org/3/library/re.html

```python
pattern = re.compile("d")
pattern.search("dog")     # Match at index 0
<re.Match object; span=(0, 1), match='d'>
pattern.search("dog", 1)  # No match; search doesn't include the "d"
```

Kind regards,
Joris Schellekens
