### ISSUE TITLE
Can `borb` create bookmarks?

### ISSUE THREAD

**Issue by vapao** [jorisschellekens/borb#45]
Sorry, i don't see any similar examples.

![image](https://user-images.githubusercontent.com/10863906/139652048-113ae34b-843f-4e47-a46d-84a39ce85d69.png)

Like the picture above.

**Comment by jorisschellekens** [comment]
Hi there,

Yes `borb` can do that.

You are right though, there are currently no examples that showcase this.
You can find a [working example in one of the tests](https://github.com/jorisschellekens/borb/blob/master/tests/pdf/canvas/layout/heading/test_write_paragraphs_with_headings.py) though.

Kind regards,
Joris Schellekens
