### ISSUE TITLE
Slow font loading

### ISSUE THREAD

**Issue by vapao** [jorisschellekens/borb#46]
```python
from borb.pdf.canvas.layout.page_layout.multi_column_layout import SingleColumnLayout
from borb.pdf.canvas.layout.text.paragraph import Paragraph
from borb.pdf.document import Document
from borb.pdf.page.page import Page
from borb.pdf.canvas.font.simple_font.true_type_font import TrueTypeFont
from borb.pdf.pdf import PDF
from pathlib import Path


def main():
    doc = Document()
    page = Page()
    doc.append_page(page)
    layout = SingleColumnLayout(page)
    font = TrueTypeFont.true_type_font_from_file(Path('/Users/aka/Software/fonts/SimHei.ttf'))
    layout.add(Paragraph('你好世界', font=font))

    with open('a.pdf', 'wb') as f:
        PDF.dumps(f, doc)


if __name__ == '__main__':
    main()
```
![image](https://user-images.githubusercontent.com/10863906/139658588-a05fc77d-3b70-4251-9155-f0e8a943c466.png)

Performed for 40 seconds and words are crowded together. file size (a.pdf) 5.3MB.
For SimHei.ttf I used [this font](https://github.com/StellarCN/scp_zh/blob/master/fonts/SimHei.ttf).

**Comment by jorisschellekens** [comment]
From the get-go, I have to tell you that I probably can't do much about the time it takes to load the font. `borb` uses the `fonttools` library to read a font-file and parse its properties. I imagine most of those 40 seconds are spent loading the font (which is happening outside the `borb` codebase).

I also know that some fonts are simply not properly defined. A previous ticket on the `borb` library for instance claimed `borb` was unable to write Chinese text.

I explained to the person who logged that ticket that he had to use a font that actually supports Chinese characters. I tried it myself with a google font, and it worked.

https://github.com/jorisschellekens/borb/issues/35

As you can see from the output PDF there, the characters are evenly spaced.
So I am guessing the font you selected is probably poorly defined.

Kind regards,
Joris Schellekens

**Comment by jorisschellekens** [comment]
Found it.

A font can define its own `units per em`.
Normally this is always 1024 or 2048.

The font you selected has 256.
I changed `borb` to explicitly read and use this parameter.

[output_001.pdf](https://github.com/jorisschellekens/borb/files/7453479/output_001.pdf)

The fix will be present in the next release (which should be next weekend).

Kind regards,
Joris Schellekens
