### ISSUE TITLE
[Suggestion] Use the package isort in order to sort import

### ISSUE THREAD

**Issue by edd34** [jorisschellekens/borb#47]
I suggest to use the package [isort](https://pypi.org/project/isort/) in order to add consistency in the import in all file.
Here are some steps in order to get started :
1. Install isort : `pip install isort`
2. See isort errors without applying fix : `isort --check --diff .`
3. Run isort, applying fixes : `isort .`

**Comment by jorisschellekens** [comment]
I applied `isort` in the next release.
It does not always play nice with `black`. 
Since `black` is more important to me, I ran it afterwards, possibly changing/undoing some of the things `isort` has done.
