### ISSUE TITLE
what coding style do you use ?

### ISSUE THREAD

**Issue by edd34** [jorisschellekens/borb#48]
Hi,
I would like to know which coding style do you stick with in this project ? And which linting tool do you use to autoformat your code ?

- [x] Black

- [ ] Autopep8

- [ ] flake8

It could be interesting to implement and automate the autoformat feature using a tool like [tox](https://pypi.org/project/tox/). Basically tox is a tool that helps you CI/CD tasks, you could automate the formating during the CI/CD stage.

**Comment by jorisschellekens** [comment]
It's right there, atop the readme.

**Comment by jorisschellekens** [comment]
Feel free to create a pull-request that implements black formatting.

This is what I would prefer:
- code is automatically formatted using black
- changes to the code for this automation are run after every commit
- changes to the code for this automation have their own separate commit
- the script or automation should be extensible. There's another issue about running isort, it would be great if I could include that.

Kind regards,
Joris Schellekens

**Comment by edd34** [comment]
Alright, I'll work on this feature, thanks for the clear feedback 😀

**Comment by jorisschellekens** [comment]
Hi there,

If you want your name on this feature/commit, you will have to provide me with a signed copy of the contributor agreement, which you can find in the repository.

Kind regards,
Joris Schellekens

**Comment by edd34** [comment]
> Hi there,
> 
> If you want your name on this feature/commit, you will have to provide me with a signed copy of the contributor agreement, which you can find in the repository.
> 
> Kind regards, Joris Schellekens

I have sent it over by mail

**Comment by jorisschellekens** [comment]
You sent an email, where you copy/pasted the contributor agreement.
Your "signature" contains only your name in plaintext (rather than an actual image of your signature for instance, or providing me with a signed email).

I can not, in good conscience accept a plaintext, easily-copyable piece of text as a signature.

Kind regards,
Joris Schellekens
