### ISSUE TITLE
HeterogeneousParagraph does not wrap

### ISSUE THREAD

**Issue by decherd** [jorisschellekens/borb#49]
It doesn't seem that the HeterogeneousParagraph has a way of wrapping a long passage of text and working similar to Paragraph.

I am using a list of (3) ChunkOfText() with the first being before the bold text, the second the bold text, and the third the text following the bold word to try to create this:

"Lorem **ipsum** dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."

I'm getting a: ValueError: max() arg is an empty sequence

I am using layout.add() to add the HP to the layout so that I don't have to provide a bounding box similar to how I would use a regular paragraph.

It seems the HeterogeneousParagraph does not have a bounding box.

Any suggestions?

**Comment by jorisschellekens** [comment]
Hi there,

Can you please share the code-snippet you're using?
Because wrapping of HeterogeneousParagraph is something I test.

https://github.com/jorisschellekens/borb/blob/master/tests/output/test_write_chunks_of_text/output_001.pdf

Kind regards,
Joris Schellekens

**Comment by decherd** [comment]
I see my problem after looking at your tests. You mentioned in your documentation that ChunkOfText is the atomic element for rendering but I was passing in a longer chunk of text thinking it would be able to break up the chunks being passed in to the HeterogeneousParagraph after they were combined. 

`doc: Document = Document()
page: Page = Page()
doc.append_page(page)

layout: PageLayout = SingleColumnLayout(
    page,
    horizontal_margin=Decimal(32),
    vertical_margin=Decimal(16),
)
chunks_of_text = [
    ChunkOfText(
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. "
    ),
    ChunkOfText(
        "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. "
    ),
    ChunkOfText(
        "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
    ),
]
layout.add(HeterogeneousParagraph(chunks_of_text))

with open("output.pdf", "wb") as out_file_handle:
    PDF.dumps(out_file_handle, doc)`

I guess I'll have to split the chucks on spaces and add them to a list as I build that up before passing it to the HeterogeneousParagraph.

Thanks for the reply!

**Comment by jorisschellekens** [comment]
No problem, happy to help.

Kind regards,
Joris Schellekens

**Comment by vachalasani** [comment]
@jorisschellekens I'm facing the same problem. I receiving the text chunk dynamically from JSON and I cant manually chunk it. I'm getting this error. 
AssertionError: HeterogeneousParagraph is too wide t
o fit inside column / page. Needed 1143 pts, only 476 pts available.

This below is an example chunk that's throwing this error.

chunks_of_text = [
            ChunkOfText(
                "If you need help reading or completing this document or need help communicating with us, ",
                font='Helvetica Bold',
                font_size=Decimal(os.getenv('regularfont'))
            ),
            ChunkOfText(
                "ask us or call 1-877-423-4746. Our services, including interpreters, are free. If you are deaf, hard-of-hearing, deaf-blind or have difficulty speaking, you can call us at the number above by dialing 711 (Georgia Relay). "
            ),
        ]
        layout.add(HeterogeneousParagraph(chunks_of_text))
        
Appreciate your help on this! Thank you.

**Comment by jorisschellekens** [comment]
Hi @vachalasani,

Based on the text you are trying to insert, I would say you work for the Georgia Department of Human Services.
To the best of my knowledge they do not have a commercial license for borb, and as a result (in order to abide by the license terms) should publicize their code.

Can you point me towards the public Github repository that contains this code?

Kind regards,
Joris Schellekens
