### ISSUE TITLE
How to avoid blank lines between Paragraphs added to layout

### ISSUE THREAD

**Issue by decherd** [jorisschellekens/borb#50]
Is there a way to modify a Paragraph so that subsequent Paragraphs don't have blank lines between them? If not, is there a better class to use to achieve this effect while still having the PageLayout help with creating the bounding boxes for me?

**Comment by jorisschellekens** [comment]
Hi there,

MultiColumnLayout has 2 parameters (use one of the 2) to set the amount of space between Paragraph objects.

https://github.com/jorisschellekens/borb/blob/a49650394d7f1ee14a2b960ad003f8716e8725ce/borb/pdf/canvas/layout/page_layout/multi_column_layout.py#L30

Kind regards,
Joris Schellekens

**Comment by decherd** [comment]
Thank you Joris for the response. That works perfectly. 

I'm adding the snippet below for future folks searching for this:
`layout: PageLayout = MultiColumnLayout(
    page,
    number_of_columns=1,
    fixed_paragraph_spacing=Decimal(0.5)
)`
