### ISSUE TITLE
Possible to add Japanese characters supports

### ISSUE THREAD

**Issue by LennyLiuOYO** [jorisschellekens/borb#51]
Hey Joris
While I was using your library to create some invoice PDFs, I ran into some errors with Japanese/Chinese characters
Sample code:
```
pdf = Document()
page = Page()
pdf.append_page(page)
page_layout = SingleColumnLayout(page)
page_layout.vertical_margin = page.get_page_info().get_height() * Decimal(0.05)
table_001 = Table(number_of_rows=5, number_of_columns=3)
table_001.add(Paragraph("請求書.",font='Courier', horizontal_alignment=Alignment.CENTERED))
```
Error:
`assert cid is not None, "Font %s can not represent '%s'"`
I tracked the error from borb/pdf/canvas/layout/text/chunk_of_text.py._write_text_bytes_in_hex

請 = chr(0x8acb)
求 = chr(0x6c42)
書 = chr(0x66f8)
Do you mind taking a look, please?
Thanks

**Comment by jorisschellekens** [comment]
Hi there,

This is not a bug.
borb is telling you (literally) that the font you are using does not contain that character.

Some fonts don't contain all characters. 
Use the appropriate font (one containing Japanese characters) and the assert will be gone.

It would help if you looked through the closed issues.

https://github.com/jorisschellekens/borb/issues/35

Kind regards,
Joris Schellekens

**Comment by LennyLiuOYO** [comment]
I downloaded a Japanese Font, it's working fine now.

Thanks, Joris
