### ISSUE TITLE
[Suggestion] requirements and single page loading

### ISSUE THREAD

**Issue by Hammy27** [jorisschellekens/borb#53]
Hi Joris

Two small suggestions:
- would it be possible (don't know the dependencies) to allow setuptools>=51.1.1 instead of setuptools~=51.1.1? Had to downgrade setuptools in my test project as other (conda managed) packages used 52.0.0.
- Would it be possible to add an additional argument to the `PDF.loads()` method to indicate what pages you want to load. Something like `PDF.loads(pdf_file, [l], [0])` or `PDF.loads(pdf_file, [l], [0;3])`. Use case would be that I'm playing with borb to extract some snippets of text and then use language detection to guess the language present in the file, where most of the times one page would be more than sufficient. Loading every page causes a bit of memory usage which at least in my case slowed the process down a bit.

Anyways, awesome work so far!

**Comment by jorisschellekens** [comment]
Hi Hammy,

I'll try to see which dependencies can be specified in which version (in the next release).

With regards to loading a specific page by giving an argument, I'd prefer not to do it that way.
My idea (which I will hopefully get the time for one of these days :smile: ) was to have lazy evaluation. Where reading the content of a `Page` is delayed until some `EventListener` actually asks for it.

Kind regards,
Joris Schellekens

**Comment by Hammy27** [comment]
Ok, perfect. I guess this would be a big advantage. I tried using borb on an AWS instance. Unfortunately when parsing the pdf it took so long, that the instance basically crashed (setup was django/nginx/gunicorn/docker). I guess the lazy evaluation would be a big plus especially for people using the package within a low to medium-tier Setup.

**Comment by jorisschellekens** [comment]
Dependencies have been updated in the new release. Lazy loading was already a feature on my road map.

So I'm going to close this ticket.

Thanks for taking the time to give feedback 🙂 

Kind regards,
Joris Schellekens
