### ISSUE TITLE
How to return document from API as a filestream

### ISSUE THREAD

**Issue by gwenf** [jorisschellekens/borb#54]
I'm trying to figure out how to return a PDF document directly from an API. All of the examples you have show it being saved to, or read from, a file. Do you have any suggestions or code examples to show how to convert it to a bytestream so I can return it without having to save the file?

Thanks.

**Comment by jorisschellekens** [comment]
I think this issue is completely unrelated to `borb`.
`borb` allows you to persist a document to anything that supports writing bytes to it.

Check out the documentation for [BytesIO](https://docs.python.org/3/library/io.html#io.BytesIO) to learn more about how to work with byte streams.

Kind regards,
Joris Schellekens

**Comment by gwenf** [comment]
Yeah, I was using BytesIO and it worked with Reportlab, but It's not working the same way with Borb. I'll figure it out though, thanks.

**Comment by gwenf** [comment]
I want to post here in case someone else is having this issue.
I basically ended up solving this problem by turning it into a Base64 encoded string (without turning it into Base64, the PDF would be blank). Here is the code on my API:

```py
# this code is inside of a Django view
buf = io.BytesIO()
PDF.dumps(buf, pdf)
buf.seek(0)

return HttpResponse(b64encode(pdf.getvalue()).decode("utf-8"))
```

And here is the front-end code:
```js
const url = `data:application/pdf;base64,${res.data}`
const link = document.createElement('a')
link.href = url
link.setAttribute('download', 'report.pdf')
document.body.appendChild(link)
link.click()
```

I don't know if it's the best solution, but it works well.
