### ISSUE TITLE
Ability to Set Document Meta-information

### ISSUE THREAD

**Issue by KwilliamAB** [jorisschellekens/borb#60]
Hi,

Is there currently anyway to set meta-information when creating a PDF file?  ie.  Author, Title

Thanks

**Comment by jorisschellekens** [comment]
Hi there,

That's certainly possible.

`borb` converts any PDF to a JSON representation. Setting the meta-information is a matter of setting the right key/value pairs in the JSON.

One of the tests in the repository explicitly sets these meta information key/value pairs and then verifies the document by reading it and checking the tags.

You can find that test here.

https://github.com/jorisschellekens/borb/blob/710eb5d53e5ee135f221255453cc18accde9031f/tests/pdf/conformance/test_write_pdf_a_1b.py

Kind regards,
Joris Schellekens
