### ISSUE TITLE
Setting Vertical Margin Leaves Page Unchanged

### ISSUE THREAD

**Issue by autsauce** [jorisschellekens/borb#62]
I am following the code from the invoice example, however, the code that is supposed to adjust the vertical margin to fit a logo does not reduce the margin.

` pdf = Document()
  page = Page()
  pdf.append_page(page)

  page_layout = SingleColumnLayout(page)
  page_layout.vertical_margin = page.get_page_info().get_height() * Decimal(.02)`

**Comment by jorisschellekens** [comment]
Try the following snippet (using the latest version of `borb` of course):

```
from decimal import Decimal

for i in [0.1, 0.2, 0.3, 0.4]:

  page = Page()
  pdf.append_page(page)

  layout = SingleColumnLayout(page)
  layout._vertical_margin = Decimal(842 * i)
  layout.add(Paragraph("Hello World!"))
```
