### ISSUE TITLE
Writing long URL in PDF throws error

### ISSUE THREAD

**Issue by ShramanaT** [jorisschellekens/borb#64]
I need to write long URLs in a PDF and the text is not wrapped onto a newline. Is there any workaround for this? It throws this error:
`Paragraph is too wide to fit inside column / page.`

P.S. Great job with the package!

**Comment by jorisschellekens** [comment]
Hi,

The error is telling you that the paragraph is not wide enough to contain the URL.

I assume you're not using hyphenation. But even you were, hyphenation is not going to split a URL.

So the layout algorithm of paragraph is forced to try to fit your long URL on a single line. Which it can't. Hence the error.

I can't solve your problem. You're attempting to squeeze a piece of content into an area that's too small to contain it.

Possible workarounds:
- shorter URL
- smaller font
- use annotations to have a sticky note pop up with the entire URL
- actually use a URL annotation so the document just contains a hyperlink

There are examples for all of these in the examples repository. 

Kind regards,
Joris
