### ISSUE TITLE
Sales form does not show success/ failure messages

### ISSUE THREAD

**Issue by ShramanaT** [jorisschellekens/borb#65]
Hi! I find this package very useful to develop my company's internal reporting tool. It would be good to get in touch through the [sales form](https://borbpdf.com/contact) but unfortunately it neither shows 'successfully submitted' or 'failed to send', so I am not sure if my messages reached you.

Nevertheless, it maybe a good idea to add these messages to the form for ease of understanding.

**Comment by jorisschellekens** [comment]
Hi there,

Thanks for alerting me of this bug.

I've talked to our website designer, he'll get right on it. It may be temporarily replaced by simple mailto link while he debugs the issue.

In the meantime, feel free to email me at borbpdf@gmail.com 

Kind regards,
Joris Schellekens
