### ISSUE TITLE
Error when deploying to Heroku

### ISSUE THREAD

**Issue by vincentcccheng** [jorisschellekens/borb#66]
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
borb 2.0.17 requires setuptools~=51.1.1, but you have setuptools 57.5.0 which is incompatible.

I had a trouble with the above and hope you can help.  Thanks!

**Comment by jorisschellekens** [comment]
It'll be updated in the next version of `borb`. 
Which should be released this weekend.

**Comment by jorisschellekens** [comment]
Should be fixed.

**Comment by vincentcccheng** [comment]
Hi Joris,

Thanks so much.    Just tested and it worked great !!

Vincent

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
