### ISSUE TITLE
Setuptools dependency is old

### ISSUE THREAD

**Issue by noamsgl** [jorisschellekens/borb#67]
Hi!

First of all, thanks for this awesome package, it has been very helpful to me.

My issue is with the dependency requirement:
`"setuptools~=51.1.1"`

https://github.com/jorisschellekens/borb/blob/c6ea9ecf7a9da68c46cd950e4397da42a34098e3/setup.py#L22

This dependency is causing my dependency manager (Pipenv) to fail because other packages require different ("==59.5.0") setuptools versions.

Is there any reason for this requirement? Can you update the package to something like `"setuptools>=51.1.1"`?

Thanks again!

**Comment by jorisschellekens** [comment]
It'll be updated in the next version of `borb`. 
Which should be released this weekend.

**Comment by jorisschellekens** [comment]
Should be fixed.
