### ISSUE TITLE
accessing encrypted documents

### ISSUE THREAD

**Issue by stefanseefeld** [jorisschellekens/borb#75]
I'm trying to programmatically fill out government forms using `borb`, and I ran into assertion errors / exceptions in the highlighted section in https://github.com/jorisschellekens/borb/blob/master/borb/io/read/reference/xref_transformer.py#L98-L136
(the values of `r` and `v` are `4` and `4` respectively). Any idea whether such versions will be supported eventually ?

**Comment by jorisschellekens** [comment]
Hi Stefan,

I would to be able to handle password-protected PDF documents, but I haven't yet gotten around to implementing that feature.
Keep in mind `borb` is also a one-man project that I do in my spare time. So it is very hard to predict when I will finish a feature/release. So I can not really give you a timeline or estimate.

Kind regards,
Joris Schellekens
