### ISSUE TITLE
Possible to write text onto an existing PDF at a specific x and y position?

### ISSUE THREAD

**Issue by Spenhouet** [jorisschellekens/borb#76]
We just discovered this well maintained and nicely documented library but I could not figure out if it works in our use-case.

We have an existing PDF (we generated with weasyprint from HTML templates).
The target PDF viewers do not work with form fields, so they are out of the picture.

In these existing PDFs we want to write text onto certain pages with a specified position (x, y coordinates) with a configured text size and font.

We could not figure out if this is possible with borb. At least the documentation here does not seem to contain any information on that: https://github.com/jorisschellekens/borb-examples
The "TextField" does not seem to provide that functionality.

**Comment by jorisschellekens** [comment]
You can easily add any `LayoutElement` implementation to a `Page` at an exact location.

There are some examples that will show you how to do this. Mostly those in chapter 2, related to positioning and alignment of `Paragraph` objects.

Essentially you need to call `element.layout(page, rectangle)`. Where `page` is the `Page` you'd like to add content to, and `rect` is the bounding box in which you'd like to place the element.

Kind regards,
Joris Schellekens

**Comment by Spenhouet** [comment]
Hi @jorisschellekens,

thanks for pointing me into the right direction. This does in fact seem to be what I was looking for.
I have some starting issue in that the text does not render where I placed and is also mirrored.
But I will look further into it and raise issues when I encounter them.

Great library btw. I'm also pretty frustrated with the state of PDF libraries in Python and did not know about borb before.

Best regards,
Sebastian Penhouet

**Comment by 411A** [comment]
Hi, I just find this great library (thank you so much! @jorisschellekens) and have the same question (Adding text on existing PDF), I wish there was a code on chapter 5.1 or 6.1, did this:
```python
page: Page = doc.get_page(0)

r: Rectangle = Rectangle(
        Decimal(59),                # x: 0 + page_margin
        Decimal(848 - 84 - 100),    # y: page_height - page_margin - height_of_textbox
        Decimal(595 - 59 * 2),      # width: page_width - 2 * page_margin
        Decimal(100),               # height
    )

Paragraph("Hello World!").layout(page, r)
```
But I'm getting a corrupted strange PDF! (it's only on existing pdf, code works fine on a newly created pdf). am I doing something wrong?
This is what I get:
<img src="https://user-images.githubusercontent.com/13054619/158075009-eb8f6b71-ef0c-423a-96c5-1d96664e12d1.png" width="200" height="280">

**Comment by jorisschellekens** [comment]
Hi @411A

Can you create a new ticket with your issue?
And please attach the full code snippet and the source pdf you are using (since you already mentioned that creating the pdf from scratch works)

Kind regards,
Joris Schellekens
