### ISSUE TITLE
Assertion error

### ISSUE THREAD

**Issue by PaoloBezzina** [jorisschellekens/borb#79]
I am trying to build an app which creates an invoice. Whenever I run the program normally, everything works fine. The library functions perfectly, and the formatting options are brilliant. 

However whenever i try using the "Auto Py to Exe" library, to compile a .exe file i get an 'Assertion error' for this library nesting to the font_type_1.py file. (see image attached).

![image](https://user-images.githubusercontent.com/72805355/156376759-831c88ce-8375-4797-b12e-1f122fa9748d.png)

**Comment by jorisschellekens** [comment]
The assert goes of whenever the afm directory can not be found.

The PDF spec defines 14 fonts as in-built. Meaning any software that renders a PDF should be able to handle those fonts without having the actual font file.

Nevertheless, whenever you use one of those fonts you need to provide some minimal info.

That is why you have an `afm` directory in borb. `afm` stands for Adobe Font Metrics.

I'm guessing that the code or program you are using to convert your python script into an app does some optimizations and removes any non-python files from the final executable.

Hence the assert. You're adding some text to the document, by default you are using one of these built-in fonts. `borb` then goes looking for the `afm` directory and can no longer find it.

**Comment by jorge1993** [comment]
How do you have solved?
