### ISSUE TITLE
"mportError: cannot import name 'Document' from 'borb.pdf.document'"

### ISSUE THREAD

**Issue by israeliano** [jorisschellekens/borb#80]
Just as the title says, I cannot import "Document".

I'm trying to run the code example from [here](https://stackabuse.com/creating-a-pdf-document-in-python-with-borb/): 

```
from borb.pdf.document import Document
from borb.pdf.page.page import Page
from borb.pdf.pdf import PDF

# Create an empty Document
document = Document()

# Create an empty page
page = Page()

# Add the Page to the Document
document.append_page(page)

# Write the Document to a file
with open("output.pdf", "wb") as pdf_file_handle:
    PDF.dumps(pdf_file_handle, document)
```

and I get

`ImportError: cannot import name 'Document' from 'borb.pdf.document'`

Currently running borb 2.0.20 on linux.

**Comment by jorisschellekens** [comment]
Hi,

The tutorial is old and its imports are no longer up to date. I would recommend you use the official repositories whenever you want code samples that work.

The import should be:
`from borb.pdf.document.document import Document`

You'll see the difference in the code sample in the `README` as well.

Kind regards,
Joris Schellekens
