### ISSUE TITLE
Gray PDF background after adding text to the existing PDF

### ISSUE THREAD

**Issue by 411A** [jorisschellekens/borb#83]
Hi, I'm new to this great library; I've added a text to the existing PDF but I'm getting a corrupted PDF like the image below:
<img src="https://user-images.githubusercontent.com/13054619/158075009-eb8f6b71-ef0c-423a-96c5-1d96664e12d1.png" width="200" height="280">
I don't know if I used something wrong or it's from my input PDF...
**The code I've used**:
https://textbin.net/raw/9k9mk4qgqq
**The PDF file**:
[Planner.pdf](https://github.com/jorisschellekens/borb/files/8242320/Planner.pdf)
**Output PDF file**:
[output.pdf](https://github.com/jorisschellekens/borb/files/8242344/output.pdf)

**Comment by 411A** [comment]
I've re-downloaded the pdf and it's working fine, I'll close this issue, thanks for your great library and your kind support, keep up the good work.

**Comment by jorisschellekens** [comment]
I suspect this is what happened (and I may be completely wrong).

The pdf might be a linearized/optimized pdf document.

Let me explain; you should think of a pdf document like a json object. Pdf has primitive types (number, string, bool, etc) and aggregation types (dictionary, list, and stream for binary information).

Objects can reference each other. To accommodate this, pdf has a cross-reference table (usually abbreviated to xref).

So a stream of rendering instructions in a page object might say "use the font at reference 18". Which results in a lookup in the xref.

The xref is traditionally stored at the end of a pdf. This is sometimes unpractical, especially so in a Web context where you would typically start downloading the file at the start bytes (implying the rendering needs to wait until the final byte is downloaded).

Optimized pdf documents contain smaller xref tables throughout, to enable readers to render content as the document is being downloaded.

You could have downloaded a corrupt pdf, where part of the xref was missing (thus no reference to the background, resulting in a default gray color).

Finally, I would like to thank you for your kind words.
I hope you enjoy using the library. 

Kind regards,
Joris Schellekens
