### ISSUE TITLE
change color of extracted text

### ISSUE THREAD

**Issue by eairobotics** [jorisschellekens/borb#84]
What is the best way to change the color of the extracted text while keeping the rest of the layout exactly the same? Currently, it looks like you can only change font color by adding a layout element. However, you have to then know the coordinates of the rectangle for the original document.

Thanks!

**Comment by jorisschellekens** [comment]
This is not going to be easy to do.
PDF parsing in `borb` attempts to bring the internal structure of PDF to a more understandable format.

But there is a cut-off. When designing the library I decided that some very low-level syntax was not going to get translated into an object-oriented framework.

Page content streams are one of those. And it so happens that the rendering instructions (e.g. drawing text, changing fonts, changing colors) are all part of the page content stream.

That's the bad news. Here's the good news:

1. You could look for the exact coordinates of the text using one of the `EventListener` implementations. The examples repository is a great resource for code snippets on this. Once you have the exact coordinates, you can remove the text at this position using `RedactAnnotation`. And then you can re-insert content at the given location, in the right color.
2. You could have a look at how `borb` handles redaction. That code is performing a task very similar to what you are looking for, which is modifying the content stream.
3. You could write your own implementation of `ReadTransformer' and start storing the content instructions as objects. That would make it easier to later modify them. You would also need to create an implementation of `WriteTransformer`.
4. You could manipulate the content stream of a page directly (on the byte level) and modify the rendering instructions. You will find a reference of the most common page content operators in the `borb` repository. 

Kind regards,
Joris Schellekens
