### ISSUE TITLE
Matplotlib is not declared as a dependency

### ISSUE THREAD

**Issue by akx** [jorisschellekens/borb#86]
**Describe the bug**

Borb seems to require Matplotlib, but Matplotlib is not a declared dependency.

**To Reproduce**
Steps to reproduce the behaviour:

```python
$ pip install borb
...
Successfully installed Pillow-9.0.1 borb-2.0.22 certifi-2021.10.8 charset-normalizer-2.0.12 fonttools-4.31.2 idna-3.3 python-barcode-0.13.1 qrcode-7.3.1 requests-2.27.1 urllib3-1.26.9
$ python
Python 3.9.10 (main, Jan 15 2022, 11:48:15)
[Clang 12.0.0 (clang-1200.0.32.29)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from borb.pdf import PDF
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "site-packages/borb/pdf/__init__.py", line 61, in <module>
    from .canvas.layout.image.chart import Chart
  File "site-packages/borb/pdf/canvas/layout/image/chart.py", line 12, in <module>
    import matplotlib.pyplot as MatPlotLibPlot  # type: ignore [import]
ModuleNotFoundError: No module named 'matplotlib'
>>>
$
```

**Expected behaviour**

The package should work out of the box after being installed.

In other words, all hard dependencies should be installed when installing `borb`, or if the dependency is not hard (I'm not going to do chart layout, and the import in that particular module is only used for a type annotation...), they should maybe be extras.

**Desktop (please complete the following information):**
 - OS: macOS 10.15.7
 - borb version: 2.0.22

**Comment by jorisschellekens** [comment]
fixed in `v2.0.22.2`
