### ISSUE TITLE
Upload created pdf to given URL

### ISSUE THREAD

**Issue by Balaganesh88** [jorisschellekens/borb#89]
Is there any existing way to upload the pdf generated from the PDF.dumps() method directly into a given URL? If not, can it be done?

**Comment by jorisschellekens** [comment]
This is not a question about the `borb` library, but about `io` in Python.

`borb` can output a pdf into a file or bytebuffer (for more information about that, check some of the closed issues).

Once you have the bytes, you can push them to a server. But again, that's a question about general `io`.
