### ISSUE TITLE
Page Layout without margins

### ISSUE THREAD

**Issue by Balaganesh88** [jorisschellekens/borb#90]
I couldn't find any option to create a page without any margins. Is there a way for it in the current version?

**Comment by jorisschellekens** [comment]
If I look at `MultiColumnLayout` for instance, its constructor accepts a `horizontal_margin` and `vertical_margin` attribute.

Have you tried those?
If you have, and they don't work, log a bug.

**Comment by Balaganesh88** [comment]
Oh yes, it works when I give the margins in the constructor while creating the page_layout. Thanks for the help
