### ISSUE TITLE
BUG: Instantiating `PDFToJPG` raises an exception on a Mac

### ISSUE THREAD

**Issue by strickvl** [jorisschellekens/borb#91]
**Describe the bug**
I'm trying to use `PDFToJPG.convert_pdf_to_jpg` to convert a PDF into a JPG file, but calling it as part of my code raises an exception.

**To Reproduce**
Steps to reproduce the behaviour:

```python
from borb.toolkit.export.pdf_to_jpg import PDFToJPG
test: "PDFToJPG" = PDFToJPG()
```

I get the following stack trace:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/xxx/.pyenv/versions/redaction-model/lib/python3.8/site-packages/borb/toolkit/export/pdf_to_jpg.py", line 52, in __init__
    self._find_font_families()
  File "/Users/xxx/.pyenv/versions/redaction-model/lib/python3.8/site-packages/borb/toolkit/export/pdf_to_jpg.py", line 67, in _find_font_families
    if f.is_dir():
AttributeError: 'NoneType' object has no attribute 'is_dir'
```

**Expected behaviour**
I didn't expect an error to get raised. I took a look at how it's being tested and I guess maybe it's only being tested on a Linux environment? (which is why `None` is never passed in as `file_stk` on line 63 [here](https://github.com/jorisschellekens/borb/blob/master/borb/toolkit/export/pdf_to_jpg.py). I couldn't find any Github Actions scripts in the repository for testing on multiple environments which is what led me to suspect this.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Mac 
 - borb version [e.g. 22]  2.0.22.2
- input PDF (if applicable) NA (didn't even get that far)

**Additional context**

**Comment by jorisschellekens** [comment]
You are right, we currently don't test on mac.
Do you happen to know the root font directory in mac?

**Comment by jorisschellekens** [comment]
Should be fixed in new release

**Comment by strickvl** [comment]
@jorisschellekens Thank you!
