### ISSUE TITLE
DCTDecode filter implementation for PDF

### ISSUE THREAD

**Issue by gtlt** [jorisschellekens/borb#92]
Trying to use the [OCR on PDF example](https://github.com/jorisschellekens/borb-examples#72-performing-ocr-on-a-pdf) results in the following error:
```
assert False, "Unknown /Filter %s" % filter_name
AssertionError: Unknown /Filter DCTDecode
```
[stream_decode_util.py](https://github.com/jorisschellekens/borb/blob/master/borb/io/filter/stream_decode_util.py) lacks DCTDecode filter implementation. Currently implemented filters are:
```
if filter_name in ["FlateDecode", "Fl"]:
(...)
if filter_name in ["ASCII85Decode"]:
(...)
if filter_name in ["LZWDecode"]:
(...)
if filter_name in ["RunLengthDecode"]:
(...)
```

**Comment by jorisschellekens** [comment]
Please use the issue template.
It prevents me from having to ask the same questions every time.
Such as:
- what is the exact code you ran?
- what is your input PDF?
- what version of `borb` did you use?

**Comment by jorisschellekens** [comment]
You have not provided me with your exact code, or your input document.
I am closing this ticket.
