### ISSUE TITLE
All Rubber Stamp Annotation do not work

### ISSUE THREAD

**Issue by vsupacha** [jorisschellekens/borb#93]
**Describe the bug**
Trying to use Rubber Stamp Annotation, but it does not generate any image + dump data stream

**To Reproduce**
1. Write Python code based on test_add_all_rubber_stamp_annotations/
2. Generate PDF file, but no Rubber Stamp symbol on the output
3. Data is dumped as the outcome of add_annotation() code
{<borb.io.read.types.Name at 0x28639af4bb0>: <borb.io.read.types.Name at 0x28639ad6a30>,
 <borb.io.read.types.Name at 0x28639af4880>: [Decimal('0'),
  Decimal('0'),
  Decimal('612'),
  Decimal('792')],
 <borb.io.read.types.Name at 0x28639ad69d0>: {<borb.io.read.types.Name at 0x28639ad6df0>: {<borb.io.read.types.Name at 0x28639ad6670>: {<borb.io.read.types.Name at 0x28639ac6340>: <borb.io.read.types.Name at 0x28639ad6160>,
....

```python
page_width: Decimal = PageSize.A4_PORTRAIT.value[0]
page_height: Decimal = PageSize.A4_PORTRAIT.value[1]
s: Decimal = Decimal(100)
page.append_annotation(
    RubberStampAnnotation(
        Rectangle(
            page_width / Decimal(2) - s / Decimal(2),
            page_height / Decimal(2) - s / Decimal(2),
            s,
            s,
        ),
        name=RubberStampAnnotationIconType.CONFIDENTIAL,
    )
)
```

**Expected behaviour**
1. Expect Rubber Stamp logo to appear.
2. Cross-checked with test_add_all_rubber_stamp_annotations/output.pdf -> no image is displayed

**Desktop (please complete the following information):**
 - OS: Windows
 - Python 3.9
 - borb version 2.0.24
- input PDF: blank page

**Additional feedback:**
Example code in borb-examples use `append_stamp_annotation()` which is not valid in current borb version.

**Comment by vsupacha** [comment]
Just change to Acrobat Reader DC to view file. Rubber Stamp is ok. May be the issue with PDF preview on MS Edge I used.

**Comment by jorisschellekens** [comment]
Some pdf viewers don't support all features. Stamps is one example. Same with javascript and forms.

**Comment by vsupacha** [comment]
Thank you for your great work. At first, I planned to use Rubber Stamp to show DRAFT on the document. While not aware about PDF viewer, I have used two layouts on the same page to realize a simple watermark. This may gain some use cases in document generation.

**Comment by asweigart** [comment]
On Adobe Acorbat Reader DC (22.001.20117) (32-bit) on Windows 10 I see a box with diagonal lines where the stamp should be after running chapter_006/snippet_005.py. On SumatraPDF v3.1.2 I don't see anything. I'm not sure what you can do with this info, but I wanted to post it here.
