### ISSUE TITLE
Set starting index for ordered lists

### ISSUE THREAD

**Issue by engeir** [jorisschellekens/borb#94]
When working with ordered lists, I could not figure out how to continue the list order, e.g. from one table cell to the next, or if there is a paragraph of text between two lists.

I already tried implementing it myself on [this fork](https://github.com/engeir/borb/tree/add-list-start-index). Here, I add one extra parameter to the `List` class: `start_index` with default `ìnt(1)`. This is passed on to the `_get_bullet_layout_element` method call, thus the `+ 1` is removed from the implementation of `_get_bullet_layout_element` in class `OrderedList`.

Is this already possible with borb? If not, and if this is a desired feature, I could make a PR from my branch.

__MWE:__

```python
from decimal import Decimal
import borb.pdf as pdf
from borb.pdf.canvas.geometry.rectangle import Rectangle


def main() -> None:
    doc = pdf.Document()
    page = pdf.Page()
    doc.append_page(page)
    r: Rectangle = Rectangle(Decimal(10), Decimal(10), Decimal(500), Decimal(500))

    pdf.FixedColumnWidthTable(
        number_of_rows=1,
        number_of_columns=3,
        column_widths=[Decimal(0.33), Decimal(0.34), Decimal(0.33)],
    ).add(
        pdf.OrderedList()
        .add(pdf.Paragraph("Maecenas sit amet odio ut erat accumsan ut nunc."))
        .add(pdf.Paragraph("Phasellus eget magna et justo malesuada fringilla."))
    ).add(
        pdf.OrderedList(start_index=3)
        .add(pdf.Paragraph("Maecenas sit amet odio ut erat accumsan ut nunc."))
        .add(pdf.Paragraph("Phasellus eget magna et justo malesuada fringilla."))
    ).add(
        pdf.OrderedList(start_index=5)
        .add(pdf.Paragraph("Maecenas sit amet odio ut erat accumsan ut nunc."))
        .add(pdf.Paragraph("Phasellus eget magna et justo malesuada fringilla."))
    ).no_borders().layout(
        page, r
    )

    with open("lists.pdf", "wb") as pdf_file_handle:
        pdf.PDF.dumps(pdf_file_handle, doc)


if __name__ == "__main__":
    main()
```

**Comment by jorisschellekens** [comment]
This used to be an attribute in the `OrderedList`. I removed it because I didn't see anyone using it.

I think it's fine to keep the classes as they are (for now). It's relatively simple to subclass the `OrderedList` class and make the adjustment if needed. If I see more people needing this, I will consider adding it back to the code.

Thank you for your remark and time.

Kind regards,
Joris Schellekens
