### ISSUE TITLE
Unable to add multiple pages

### ISSUE THREAD

**Issue by amks1** [jorisschellekens/borb#98]
I don't know what I'm doing wrong here, I'm trying to add multiple pages to a document (two, for starters). The first page comes out how I want it, but the second page is always a tiny square with nothing on it:

![image](https://user-images.githubusercontent.com/68153785/165638445-ce020386-a49e-41d8-ab68-498020fb5f95.png)

![image](https://user-images.githubusercontent.com/68153785/165638496-a10149e8-8626-4e89-ba88-984fcb042e65.png)

Here's my code:

```python3
TITLE_FONT = "Helvetica-Bold"
TITLE_FONT_SIZE = 10

def add_page(page):
	TEXTBOX_HEIGHT = 100
	WIDTH_MARGIN = 150
	DIST_FROM_TOP_OF_PAGE = 136

	r: Rectangle = Rectangle(
        Decimal(WIDTH_MARGIN),  # x: 0 + page_margin
        Decimal(PageSize.A4_PORTRAIT.value[1] - DIST_FROM_TOP_OF_PAGE - TEXTBOX_HEIGHT),  # y: page_height - page_margin - height_of_textbox
        Decimal(PageSize.A4_PORTRAIT.value[0] - WIDTH_MARGIN * 2),  # width: page_width - 2 * page_margin
        Decimal(TEXTBOX_HEIGHT),  # height
    )
	Shape(
		points=LineArtFactory.rectangle(r),
		stroke_color=HexColor("#ffffff"),
		fill_color=HexColor("ffffff"),
	).layout(page, r)

	header_table = FixedColumnWidthTable(6, 2)

	for i in range(12):
		alignment = Alignment.LEFT if i % 2 == 0 else Alignment.RIGHT
		header_table.add(TableCell(Paragraph(
				f"TEST {i}", 
				horizontal_alignment=alignment,
				font=TITLE_FONT,
				font_size=TITLE_FONT_SIZE
			), border_bottom=False, border_top=False, border_left=False, border_right=False)).set_padding_on_all_cells(1, 0, 1, 0)
		
	header_table.layout(page, r)
	

def pages_test():
	pdf_doc = Document()

	page1 = Page()
	pdf_doc.append_page(page1)
	add_page(page1)

	page2 = Page()
	pdf_doc.append_page(page2)
	add_page(page2)

```

Could you guide me please?

**Comment by jorisschellekens** [comment]
The `issues` option on GitHub is intended for issues with the library.
In other words bugs, feature requests, etc.
It is not meant for `I don't know how to do this using this library`.
You can ask your question on StackOverflow if you want. I fixed your code and can post a reply there.

Kind regards,
Joris Schellekens

**Comment by oldmanofthemountain** [comment]
amks1

For amusement, I tried running your code. After making additions (no code changes) to allow it to execute and create a pdf file, I ended up with the output you expected. Two identical pages like your page 1.

**Comment by jorisschellekens** [comment]
@oldmanofthemountain 

I know. I added the imports needed, added the part that saves the pdf, and it works. Just as expected.

I am trying to encourage people to:
- use the issue templates
- ask anything that is "how do I do this" on StackOverflow, rather than report it as a bug here

Kind regards,
Joris Schellekens
