### ISSUE TITLE
Importing Alignment still requires a chain of imports

### ISSUE THREAD

**Issue by xD34THROW** [jorisschellekens/borb#99]
**Is your feature request related to a problem? Please describe.**
I noticed on a previous issue that imports were cleaned up, however, if one wishes to use an `Alignment` constant, like so.

`from borb.pdf.canvas.layout.layout_element import Alignment`

**Describe the solution you'd like**
I propose the following change to the borb/pdf/__init__.py file, to allow importing from `borb.pdf` rather than the chain import:

```
# PageLayout
from .canvas.layout.page_layout.page_layout import PageLayout
from .canvas.layout.page_layout.multi_column_layout import SingleColumnLayout
from .canvas.layout.page_layout.multi_column_layout import MultiColumnLayout
from .canvas.layout.layout_element import Alignment
```

Or whichever suggestion you think it belongs in. Either way, I feel that the Alignment constant should be more easily accessed.

**Describe alternatives you've considered**
Only thing I can think of is continuing with the chain import. I have made this change locally but to be honest, I am afraid to touch anyone else's code this early in my time with Python!

**Comment by jorisschellekens** [comment]
fixed in upcoming release
